equinor/fusion-app-resources

- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/columns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/components/SortableTable.tsx
Also added isFetchingContract check for Sortable table
> Fixed context usage and styling for Actual mpp and active requests

- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/index.tsx
> Bugfix - Re-added request sidesheet

- src/frontend/src/api/ApiClient.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/WorkflowPopover/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/hooks/useRequestDeletion.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/index.tsx
- Added support for deleting request
- Removed content limiting css in workflow popover
> Active requests - Added support for deleting request

- src/frontend/src/api/utils.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/PositionAssignment.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/components/OrgChartCard.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/components/PositionTimeline/InstancesTimeline.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/components/PositionTimeline/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/components/PositionTimeline/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/hooks/useArrangedInstance.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/hooks/useCurrentPosition.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/hooks/useInstancesWithPosition.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/hooks/useSortedInstances.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/orgHelpers.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/tabs/DisciplineNetworkTab.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/tabs/ReportingPathTab.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/tabs/RoleDescriptionTab/PersonalTaskDescription.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/tabs/RoleDescriptionTab/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/tabs/RoleDescriptionTab/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/tabs/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/RequestDetailsSideSheet/hooks/useCurrentRequest.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/columns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/styles.less
A re-worked version of Position side sheet in Org Chart
> Actual Mpp - Position side sheet

- src/frontend/src/components/RequestProgressSidesheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/components/RequestProgressSidesheet.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/hooks/useSubmitChanges.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/AddPersonnelSideSheet/index.tsx
Also adds the ability to remove/ignore failed requests
> Clear edit personnel form

- src/frontend/src/components/RequestProgressSidesheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/hooks/useSubmitChanges.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/AddPersonnelSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelColumns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/getFilterSections.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/index.tsx
AD filter name changed to AD Status
ManagePersonnelPage - addButton is now disabled when personnel i selected
Updated the errorhandling for failed request when saving personnel. 
Will now show the error message from backend when failing. 
When trying to create a new user that already exitst, you will acutally get a proper error. 
Instead of nothing
> Some bug fixes.

- src/frontend/src/pages/ProjectPage/components/EditContractWizard/index.tsx
Replace back arrowIcon with CloseIcon
Removed navButtons for stepper
work- /bugitem:
https://dev.azure.com/statoil-proview/Fusion/_backlogs/backlog/Fusion%20Team/Epics/?showParents=true&workitem=10662
> Contract - Close/Go back edit contract

- src/frontend/src/api/ApiClient.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/hooks/useSubmitChanges.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/utils.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/RequestDetailsSideSheet/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/hooks/useEditableRequests.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/hooks/useRequestApproval.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/hooks/useRequestDeletion.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/hooks/useRequestRejection.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/getFilterSections.ts
The bug occurred since the request id was not mapped properly
- Added merge on successful request
> Active requests - Edit will put instead of post 

- src/frontend/src/api/ApiClient.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/hooks/useEditableRequests.ts
- Added check for POST in Allow header
- Added check for completed request states in useEditableRequests
> Personnel request - Check for edit rights 

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditableTable/index.tsx
When pressing enter in the Task Owner field before your search.
The selected value would be undefined instead of null.
Causing an error in the mapping of formState.
Ensuring that a null values get translated to null.
> 10671 Actual MPP - Empty task manager field causes blank screen when hitting enter

- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditableTable/components/TablePositionPicker.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditableTable/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditableTable/styles.less
And added check for undefined in Table position picker
> 10670 - Actual MPP - edit/create - Table should autoscroll to show active field fix

- src/frontend/src/models/PersonnelRequest.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/utils.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/RequestDetailsSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/columns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/CompletedRequestsPage/columns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/CompletedRequestsPage/index.tsx
And replaced created with lastUpdated in columns and for sorting of completed requests
> Removed Approve/Reject button if request is approved by company

- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/columns.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/RequestDetailsSideSheet/RequestDetails.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/RequestWorkflow/WorkflowStep.tsx
Description -> Request description
Approve SR -> Approve CR
> Bugfix - Name changes

- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditableTable/components/TablePersonnelPicker.tsx
Edit request side sheet - personnel picker
> Bugfix - Added filter for active ad status

- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/index.tsx
The JSx structure was messed up after introduction of Resource error message
> BugFix - Actual Mpp filter

- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/index.tsx
this was supposed to be removed with the introduction off ResourceErrorMessage
> Managed Personnel - removed old error handling

- src/backend/api/Fusion.Resources.Api/Controllers/Utilities/Requests/ConvertSpreadsheetRequest.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Utilities/UtilitiesController.cs
POST /utilities/parse-spreadsheet
--form 'file=@/C:/.../test-person-list.xlsx'
```
{
"headers": [
{
"cellRef": "A1",
"title": "Last Name",
"colIndex": 0
},
{
"cellRef": "B1",
"title": "First Name",
"colIndex": 1
},
{
"cellRef": "C1",
"title": "Mail",
"colIndex": 2
},
{
"cellRef": "D1",
"title": "Phone",
"colIndex": 3
}
],
"data": [
{
"index": 0,
"items": [
"[Last name]",
"[First name]",
"mail@company.com",
"[phone]"
]
},
...
],
"messages": []
}
```
> Api - Endpoint for parsing spreadsheet

- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditablePositionDetails/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/index.tsx
General tab fields rearranges according to updated design.
email moved to its own row. Dawinci moved to third row.
Added saving flag to disable save button when saving in progress.
Changed save button to show spinner when saving is in progress.
> Manage Personnel - Adjustments to PersonnelInfoSideSheet

- src/frontend/src/pages/ProjectPage/components/EditContractWizard/hooks/useAvailableContracts.ts
> Remove the mocked random contract number from available contracts

- src/frontend/src/api/env.ts
- src/frontend/src/hooks/useServiceNowPopoverRef/index.tsx
- src/frontend/src/hooks/useServiceNowPopoverRef/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/RequestDetailsSideSheet/hooks/usePositionById.ts
Changed functions base url and some visual improvements
> Bugfix - Manage Personnel - failed request service now link

- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/columns.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditableTable/index.tsx
> 11109 Required and optional fields in personnel request

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/index.tsx
Manage Personnel SideSheet header changed from Discipline to name off selected personnel.
Updated components to implement bug fixes for data table.
> Manage Personnel SideSheetheadertext change

- src/frontend/package-lock.json
- src/frontend/package.json
Ref comment from users in the user forum
> Update fusion components to fix scrollTo-bug in Edge

- pipelines/fusion-app-pipeline.yml
> Fix copy/paste bug in trigger path for frontend pipeline

- src/frontend/src/components/RequestProgressSidesheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/components/RequestProgressSidesheet.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/AddPersonnelSideSheet/index.tsx
- Saving personnel
- Saving requests
> Custom titles in progress sidesheets

- docs/role-delegation.md
- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/api/GithubApiClient.ts
- src/frontend/src/models/PersonDelegation.ts
- src/frontend/src/pages/HelpPage/index.tsx
- src/frontend/src/pages/HelpPage/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/ContractAdminTable/columns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/DelegateAccessSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ContractDetailsPage/index.tsx
- Added role delegation md to help page
- Spell checked role delegation md
- Removed "Role" column in data table and side sheet
- Ensure only CR classified delegation will be shown in data table
- Certified by column in data table will show reCertifiedBy if present
> Frontend - Minor fixes

- src/frontend/package.json
- src/frontend/src/pages/ProjectPage/components/EditContractWizard/components/ContractNumberPicker.tsx
Changed placeholder text from Contract Nr. to Contract No.
> Frontend - Changed label text on contract number picker

- src/backend/Fusion.Resources.sln
- src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
- src/backend/api/Fusion.Resources.Api/appsettings.json
- src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ContractorPersonnelRequest/CheckUserAccess.cs
- src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/ContractRoleHandlerTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Fusion.Resources.Api.Tests.csproj
- src/backend/tests/Fusion.Resources.Domain.Tests/Fusion.Resources.Domain.Tests.csproj
- src/backend/tests/Fusion.Resources.Logic.Tests/CheckUserAccessCommandTests.cs
- src/backend/tests/Fusion.Resources.Logic.Tests/Fusion.Resources.Logic.Tests.csproj
- src/backend/tests/Fusion.Resources.Test.Core/ApiContractBuilder.cs
- src/backend/tests/Fusion.Resources.Test.Core/Fusion.Resources.Test.Core.csproj
Taking delegated roles into consideration when evaluating access.
**Testing:**
Add delegated role, see that approve/reject buttons are enabled in UI.
**Checklist:**
> Request API - OPTIONS for can approve - Added delegated role processing

- src/backend/function/Fusion.Resources.Functions/Functions/ProfileSync.cs
Sync would stop processing if one person failed or was not found. Improved this, all persons will now be processed.
**Testing:**
Background job. See status in UI when account changes to verify.
**Checklist:**
> Profile sync function - Added failover if person does not exist

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditRequestSideSheet/utils.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PersonPositionsDetails/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/RequestDetailsSideSheet/index.tsx
Added support for percentage suffix
Ensure list of positions on person details for request details side sheet
> Frontend - various fixes

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/api/ApiClient.ts
- src/frontend/src/api/ResourceCollection.ts
- src/frontend/src/hooks/useServiceNowPopoverRef/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/hooks/usePositionDeletion.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/index.tsx
Added new endpoint for mpp deletion
> fix: replace delegate mpp delete endpoint

- src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
Discovered issue in integration lib, this is fixed in version 3.5.6. Bumping version in resources.
**Testing:**
Test through app
**Checklist:**
> Hotfix - Resources API - Claims transformation issue in integration lib

- src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
**Testing:**
Test through app
**Checklist:**
> Hotfix - Integration lib - Package bump

- src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
- src/backend/api/Fusion.Resources.Api/Notifications/RequestsNotificationHandler.cs
- src/backend/api/Fusion.Resources.Api/Startup.cs
> Notification - Specify app key in integration configuration.

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/RequestsController.cs
Added missing auth checks
**Testing:**
**Checklist:**
> Resources - Authorization rules not enforced

- src/backend/function/Fusion.Resources.Functions/ApiClients/INotificationApiClient.cs
- src/backend/function/Fusion.Resources.Functions/ApiClients/NotificationApiClient.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/RequestNotificationSender.cs
Now sending correct priority parameter.
**Testing:**
**Checklist:**
> Notification function - Priority not set correctly

- src/backend/function/Fusion.Resources.Functions/ApiClients/NotificationApiClient.cs
> Notification sender - Api client - Corrected priority prop name

- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/PositionV2Extensions.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/RequestNotificationSender.cs
Added extension to avoid duplication.
**Testing:**
To be tested in QA
**Checklist:**
> Functions - Active instance check fix

- src/backend/api/Fusion.Resources.Domain/Extensions/PositionV2Extensions.cs
- src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
- src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourcesApiWebAppFactory.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/ContractTests.cs
Not checking user in active instance check. Was not covered in tests, also API tests have been failing for some time in Resources.
Finally figured out why and fixed.
**Testing:**
Check user access control.
**Checklist:**
> Api - Auth check error

- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/PersonnelController.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/ContractTests.cs
Equinor CRs can now manage personnel. Also added integration tests for it.
**Testing:**
**Checklist:**
> Manage personnel - Allowing Equinor CRs access

- pipelines/api-pr-pipeline.yml
- pipelines/templates/install-fusion-ps.yml
- src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-pr-env.yml
**Testing:**
Test by triggering build on PR
**Checklist:**
> Resources - Pipelines & infrastructure for PR environments

- src/backend/api/Fusion.Resources.Api/Middleware/TraceMiddleware.cs
- src/backend/api/Fusion.Resources.Api/Startup.cs
Added TraceMiddleware
**Testing:**
Verified during local execution.
Middleware hit, and continued.
**Checklist:**
> API - TraceMiddleware

- pipelines/api-pr-pipeline.yml
- src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-pr-env.yml
There was an issue with images not being pulled by k8s when new ones were pushed.
Set image pull policy to always and touching deployment file with buildnumber to force update as well.
> Update api-pr-pipeline.yml for Azure Pipelines

- pipelines/api-pr-pipeline.yml
- src/backend/api/Fusion.Resources.Api/appsettings.json
**Testing:**
Test through builds
**Checklist:**
> API - PR pipeline - Missing required database tags.

- src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
- src/backend/api/Fusion.Resources.Api/Controllers/ApiErrors.cs
- src/backend/api/Fusion.Resources.Api/Controllers/ApiModels/CommonEntities/ApiProjectReference.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiBasePosition.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiInternalPersonnelPerson.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/PersonnelController.cs
- src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
- src/backend/api/Fusion.Resources.Api/Middleware/ApiProblem.cs
- src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
- src/backend/api/Fusion.Resources.Domain/Models/QueryBasePosition.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryDepartmentPersonnelPerson.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryPersonAbsence.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryProject.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentPersonnel.cs
Endpoint to list all personnel in a department, using the people search endpoint. 
Includes a timeline calculation used to render a timeline view.
**Testing:**
Verified with frontend. Preview endpoint, can be changed at later date.
**Checklist:**
> Department personnel endpoint

- pipelines/pr-cleanup-pipeline.yml
Added pipeline for cleaning up pull request environments. 
The pipeline use a pat token to fetch active pull requests from the github api. 
Databases are located by querying for databases with specific tags.
Aks resources are cleaned up by querying for deployments with specific labels. These are used to detect expired pull requests, for which deployments, services and ingress manifests are deleted.
**Testing:**
Verified by running pipeline. Databases and aks resources have been deleted.
**Checklist:**
> Pipelines - Added pull request cleanup pipeline

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/CreateResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/UpdateResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20210219114009_ResourceAllocationRequest_AssignedDepartment.Designer.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20210219114009_ResourceAllocationRequest_AssignedDepartment.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Create.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Update.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ResourceAllocationTestData.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
Added CRUD support for new property (AssignedDepartment) on DBResourceAllocationRequest
**Testing:**
**Checklist:**
> Resource - Internal Requests - AssignedDepartment property

- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
Workflow data should be added to requests.
Expansion of org data should consider orgPositionInstance
**Testing:**
**Checklist:**
> Resources API - Decorating requests with workflow and org data

- src/backend/api/Fusion.Resources.Logic/Workflows/InternalRequestNormalWorkflowV1.cs
- src/backend/tests/Fusion.Resources.Logic.Tests/InternalRequestNormalV1.cs
Fixed copy-paste issue in proposed function.
This should fix that the workflow jumps the proposed stage.
**Testing:**
Verified in tests
**Checklist:**
> Api - Normal request flow fix

- src/backend/api/Fusion.Resources.Domain/Queries/GetPersonProfiles.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
Resolve profiles from people when getting requests by department
**Testing:**
**Checklist:**
> Resolve profile on department requests

- src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentPersonnel.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetSectorPersonnel.cs
- src/backend/api/Fusion.Resources.Domain/Utils/TimelineUtils.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
- src/backend/tests/Fusion.Testing.Mocks.OrgService/FusionTestProjectBuilder.cs
Fix: requests timeline with overlapping dates
**Testing:**
**Checklist:**
> fix overlapping segments in timeline

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
Added endpoints for patching and getting a request using the department prefix, to align resource paths.
**Testing:**
n/a
**Checklist:**
> Added request endpoints for department

- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/RequestRouter.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
- src/backend/tests/Fusion.Resources.Logic.Tests/RequestAssignment.cs
Auto assign requests based on responsibility matrix
**Testing:**
**Checklist:**
> Auto-assign requests

- src/backend/api/Fusion.Resources.Api/Controllers/Person/ApiModels/ApiPersonAbsence.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiInternalPersonnelPerson.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbPersonAbsence.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryPersonAbsence.cs
Added missing mapping of properties in PersonnelAbsence
Added requested type in PersonAbsence enum (OtherTasks)
**Testing:**
**Checklist:**
> Absence - Missing mapping/enum value

- src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentRequestsTimeline.cs
- src/backend/api/Fusion.Resources.Domain/Utils/TimelineUtils.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
- Remove filter of timeline segments < 2 days long
- Disregard time of day when adding positions to timeline segments
**Testing:**
**Checklist:**
> Remove gaps in timeline

- .github/workflows/test-api.yml
- src/backend/api/Fusion.Resources.Logic/Workflows/AllocationJointVentureWorkflowV1.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Fusion.Resources.Api.Tests.csproj
- src/backend/tests/Fusion.Resources.Domain.Tests/Fusion.Resources.Domain.Tests.csproj
- src/backend/tests/Fusion.Resources.Functions.Tests/Fusion.Resources.Functions.Tests.csproj
- src/backend/tests/Fusion.Resources.Logic.Tests/Fusion.Resources.Logic.Tests.csproj
- src/backend/tests/Fusion.Resources.Logic.Tests/InternalRequestNormalV1.cs
- src/backend/tests/Fusion.Resources.Logic.Tests/WorkflowTests.cs
Update the circular reference issue in the joint venture workflow steps.
Added automatic tests to ensure validity for all workflow types, inheriting from WorkflowDefinition
**Testing:**
Added automatic tests to test all workflow types
**Checklist:**
> Joint venture workflow fix

- src/backend/api/Fusion.Resources.Api/Controllers/Validation/CustomValidatorExtensions.cs
Fixed casting issue when validating proposed changes in post requests.
**Testing:**
n/a
**Checklist:**
> Fixed proposed changes validator issue

- src/backend/api/Fusion.Resources.Domain/Extensions/IOrgApiClientExtensions.cs
- src/backend/api/Fusion.Resources.Logic/Extensions/JsonNetExtensions.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/ProvisionAllocationRequest.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Provision.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiInternalRequestModel.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiProjectReference.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiProposedPerson.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiWorkflow.cs
- src/backend/tests/Fusion.Resources.Logic.Tests/Fusion.Resources.Logic.Tests.csproj
- src/backend/tests/Fusion.Resources.Logic.Tests/Provisioning/AllocationTests.cs
- src/backend/tests/Fusion.Resources.Logic.Tests/Provisioning/MockRequest.cs
- src/backend/tests/Fusion.Testing.Mocks.OrgService/Api/Controllers/DraftsController.cs
- src/backend/tests/Fusion.Testing.Mocks.OrgService/Helpers/ApiPositionInstanceExtensions.cs
- src/backend/tests/Fusion.Testing.Mocks.OrgService/Helpers/PositionInstanceBuilder.cs
Updated the allocation provisioning logic to also update the future TBN instances. Refactored allocation logic to separate command instead of the base provisioning command.
As the allocation process now makes multiple http calls, the provisioning have been wrapped in a draft on the org chart.
**Testing:**
Should verify by creating allocation request and update request, to see all properties are populated when allocated.
**Checklist:**
> Allocation request provisioning

- src/backend/api/Fusion.Resources.Domain/Queries/GetSectorPersonnel.cs
> Load sectors from db

- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryInternalPersonnelPerson.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentPersonnel.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetSectorPersonnel.cs
- src/backend/api/Fusion.Resources.Domain/Utils/PeopleSearchUtils.cs
> filter subdepartments

- src/backend/api/Fusion.Resources.Domain/Models/QueryPersonnelRequest.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryRequestsTimelineItem.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetContractPersonnelRequest.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetContractPersonnelRequests.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetRequestWorkflow.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/SearchDepartments.cs
Fix compiler warnings
**Testing:**
**Checklist:**
> Fix compiler warnings

- src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentUnassignedRequests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/UnassignedRequests/DepartmentUnassignedTests.cs
- src/backend/tests/Fusion.Testing.Mocks.OrgService/Api/Controllers/PositionsController.cs
Filter out completed requests from department unassigned requests endpoint
**Testing:**
**Checklist:**
> Align filters for all/relevant unassigned requests

- src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentUnassignedRequests.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/UnassignedRequests/DepartmentUnassignedTests.cs
> Expand position instances on department unassigned requests endpoint

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20210420161657_Added request number column.Designer.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20210420161657_Added request number column.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryResourceAllocationRequest.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiInternalRequestModel.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
Added new column `Number` on the request. This number will be auto incremented for each request created.
The purpose of the column is to give us 'humans' the ability to reference a specific request, without momorizing a guid or refering to project and position...
**Testing:**
Create new request, should be given a non-zero value in return. All existing requests should be given a unique number.
**Checklist:**
> Request number property

- src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentRequestsTimeline.cs
Updated the query that fetch department request timeline, to exclude completed requests. Added support for the command to optionally include it if that should be a requirement in the future.
**Testing:**
Verified on CI data
**Checklist:**
> Excluded completed requests from department timeline

- src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentUnassignedRequests.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetTBNPositions.cs
- src/backend/api/Fusion.Resources.Domain/Utils/DepartmentUtils.cs
Changed how base position department is used when checking against the targeted department. 
Have added a check on the level difference, so not too many higher up requests are included.
**Testing:**
Verified data is trimmed, however hard to say as there is no concrete ruleset
**Checklist:**
Skipping integration tests as the ruleset is in development. Should be added when rules are more defined.
> Relevant requests and tbn position updates

- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/InitializedHandler.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/JointVentureRequestTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
Revert state change previously applied
**Testing:**
**Checklist:**
> Revert workflow state change

- src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonAbsenceController.cs
Added full control role to absence endpoints
**Testing:**
Verified with postman
**Checklist:**
> Absence admin access

- src/backend/api/Fusion.Resources.Domain/Utils/PeopleSearchUtils.cs
A typo when deserializing the payload from search results cause the allocation updated date to be null.
**Testing:**
Quick fix, not needed
**Checklist:**
> Fixed missing allocation updated date

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
Added app access to endpoints listing/fetching requests and the provision endpoint.
This will fix requests not being provisioned, due to access denied in function.
**Testing:**
Must be fixed, should be ok.
**Checklist:**
> App access to request endpoints

- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestsNotificationHandler.cs
Disable date formatting for now.
Difference between timezones in windows and linux causes failure.
**Testing:**
**Checklist:**
> API - Request notifications - disable date formatting

- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestsNotificationHandler.cs
Fixed error in description, and fixed url for accessing org project
**Testing:**
**Checklist:**
> Notification - Error in description and portalurl

- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/EnterpriseAllocationRequestStarted.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/InitializedHandler.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/ResolveSubType.cs
- src/backend/api/Fusion.Resources.Logic/Workflows/AllocationEnterpriseWorkflowV1.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Requests/ApiCreateInternalRequestModel.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/EnterpriseRequestTests.cs
Support for Enterprise Allocation Request
Similar to Direct workflow, but with validation of Proposed Person to exist.
**Testing:**
**Checklist:**
> Resource Allocation Request - Enterprise subtype

- src/backend/api/Fusion.Resources.Api/FusionEvents/OrgProjectHandler.cs
- src/backend/api/Fusion.Resources.Api/Startup.cs
- src/backend/tests/Fusion.Resources.Api.Tests/FusionEventHandlerTests/ProjectSync.cs
> Synchronize local project info with org

- src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
- src/backend/api/Fusion.Resources.Application/Fusion.Resources.Application.csproj
- src/backend/api/Fusion.Resources.Database/Fusion.Resources.Database.csproj
- src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
- src/backend/api/Fusion.Resources.Logic/Fusion.Resources.Logic.csproj
- src/backend/tests/Fusion.Resources.Api.Tests/Fusion.Resources.Api.Tests.csproj
- src/backend/tests/Fusion.Resources.Domain.Tests/Fusion.Resources.Domain.Tests.csproj
- src/backend/tests/Fusion.Resources.Functions.Tests/Fusion.Resources.Functions.Tests.csproj
- src/backend/tests/Fusion.Resources.Logic.Tests/Fusion.Resources.Logic.Tests.csproj
- src/backend/tests/Fusion.Resources.Test.Core/Fusion.Resources.Test.Core.csproj
- src/backend/tests/Fusion.Testing.Authentication/Fusion.Testing.Authentication.csproj
- src/backend/tests/Fusion.Testing.Core/Fusion.Testing.Core.csproj
- src/backend/tests/Fusion.Testing.Mocks.ContextService/Fusion.Testing.Mocks.ContextService.csproj
- src/backend/tests/Fusion.Testing.Mocks.OrgService/Fusion.Testing.Mocks.OrgService.csproj
- src/backend/tests/Fusion.Testing.Mocks.ProfileService/Fusion.Testing.Mocks.ProfileService.csproj
- src/backend/tests/Fusion.Testing.Mocks.ProfileService/PeopleServiceMock.cs
Upgraded nuget packages.
Did not upgrade function project and did not upgrade FluentValidation.AspNetCore due to breaking changes
**Testing:**
**Checklist:**
> Nuget - Upgrade and consolidate packages

- src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
- src/backend/api/Fusion.Resources.Api/appsettings.json
- src/backend/api/Fusion.Resources.Domain/Commands/Personnel/ResetAllocationState.cs
- src/backend/api/Fusion.Resources.Domain/Extensions/IOrgApiClientExtensions.cs
- src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
- src/backend/api/Fusion.Resources.Logic/Fusion.Resources.Logic.csproj
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ContractorPersonnelRequest/Provision.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Provision.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
- src/backend/tests/Fusion.Testing.Mocks.OrgService/Api/Startup.cs
- src/backend/tests/Fusion.Testing.Mocks.OrgService/OrgServiceMock.cs
Add header to all calls which makes changes in org api, which indicates to the org api that the changes are related to a specific request. This allows better tracability when looking in change log etc.
**Testing:**
Created integration tests which confirms that api calls made to org api when provisioning is including the required header and value.
**Checklist:**
> Flag changes in org with request number

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Api/ListExtensions.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequestItem.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestComments.cs
* Add options action for request comment endpoints
* Deny access to request comments for all other users than resource owners 
**Testing:**
**Checklist:**
> Add ACL for request comments

- src/backend/api/Fusion.Resources.Domain/Behaviours/RequestValidationBehavior.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Contracts/RecertifyRoleDelegation.cs
- src/backend/tests/Fusion.Resources.Api.Tests/FusionMocks/RolesClientMock.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/ContractTests.cs
When trying to recertify role delegation a validation failure is observed.
Replacing behavior logic .
**Testing:**
Local tests worked anyway.
Replaced with synchronous validation. 
Created integration test
**Checklist:**
> External personnel - Contracts - Recertify Role Delegation failure

- src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonAbsenceController.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetPersonProfile.cs
- src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
Add auth for absence controller according to security matrix.
The frontend team is a bit worried that the partial read might break frontend, so that will be implemented in a future PR
**Testing:**
**Checklist:**
> Add auth for person absence

- src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonController.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
> Resource owner acl

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/AddDelegatedResourceOwnerRequest.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Departments/AddDelegatedResourceOwner.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsController.cs
Add an endpoint to allow admins to add responsibles to a department.
**Testing:**
**Checklist:**
> Add admin endpoint to add delegated responsible to department

- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
- src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
> Add auth to personnel endpoints

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/DepartmentRequestsController.cs
- src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
Add resource owner auth to department auth endpoints
**Testing:**
**Checklist:**
> Add auth for missing department endpoints

- src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonController.cs
Add missing options endpoints for person notes
**Testing:**
**Checklist:**
> Add options endpoints for person notes

- src/backend/api/Fusion.Resources.Api/Configuration/IServiceCollectionExtensions.cs
- src/backend/api/Fusion.Resources.Api/FusionEvents/Handlers/InternalRequests/RequestCreatedHandler.cs
- src/backend/api/Fusion.Resources.Api/FusionEvents/Handlers/InternalRequests/RequestDeletedHandler.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Requests/InternalRequests/DeleteInternalRequest.cs
- src/backend/api/Fusion.Resources.Domain/Notifications/InternalRequests/InternalRequestDeleted.cs
- src/backend/integration/Fusion.Resources.Integration.Models/FusionEvents/ResourceAllocationRequestEvent.cs
ADded type and sub type to subscription events. Fixed incorrect env used for line org service.
**Testing:**
n/a
**Checklist:**
> Updated subscription event payload & fixed line org endpoint

- src/backend/api/Fusion.Resources.Domain/Queries/GetDelegatedDepartmentResponsibilty.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonControllerTests.cs
Filter non-current department delegations on profile endpoint
**Testing:**
**Checklist:**
> Filter non-current department delegations on profile endpoint

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
Updated access to include GBS departments for all requests. This is needed so Spine can add personnel.
**Testing:**
n/a
**Checklist:**
> Updated access for all requests to include GBS

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/PatchInternalRequestRequest.cs
- src/backend/api/Fusion.Resources.Application/LineOrg/LineOrgResolver.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetDepartments.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
Always fallback to line org when getting departments
**Testing:**
**Checklist:**
> Validate department correctly when patching request

- src/backend/Fusion.Resources.Authorization/Handlers/RequestCreatorHandler.cs
- src/backend/Fusion.Resources.Authorization/Handlers/TaskOwnerForPositionAuthHandler.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Authorization/CanApproveStepHandlerBase.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Authorization/UnauthorizedWorkflowException.cs
- src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
- src/backend/tests/Fusion.Testing.Mocks.OrgService/Helpers/TestPositionBuilder.cs
- Fixes AB#20094
**Testing:**
**Checklist:**
> Allow resource owners in any department to claim/assign unassigned requests

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
Allow all resource owners in PDP access to internal requests
**Testing:**
**Checklist:**
> Allow PDP resource owners

- src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
- Allow all resource owners, regardless of business unit
- Fix inconcistency between PATCH and OPTIONS auth handling
**Testing:**
**Checklist:**
> Allow all resource owners

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/CreateResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Requests/InternalRequests/CreateInternalRequest.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
Allow direct assignment of proposed person and department
**Testing:**
**Checklist:**
> Allow direct assignment of proposed person and department

- src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartments.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsController.cs
Make resource owner search case insensitive
**Testing:**
**Checklist:**
> Make resource owner search case insensitive

- src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-pr-env.yml
- src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-test-env.yml
- src/frontend/k8s/deployment.template.pr.yml
- src/frontend/k8s/deployment.template.yml
Updated the ingress manifes to the correct version for new cluster
> Updated k8s ingress version

- src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-pr-env.yml
- src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-test-env.yml
Removed resource requests on the pr apis, to reduce unneeded requests on the test cluster
> Reduced/removed k8s resource request/limis on test env/prs

- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/NotifyResourceOwnerHandler.cs
Enable mail for resource owner notifications
**Testing:**
**Checklist:**
> Notification - Resource Owner Notification should include mail

- src/backend/api/Fusion.Resources.Api/FusionEvents/Handlers/InternalRequests/RequestCreatedHandler.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Requests/InternalRequests/CreateInternalRequest.cs
- src/backend/api/Fusion.Resources.Domain/Notifications/InternalRequests/InternalRequestCreated.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
Should send notification when direct assignment during creation of request
**Testing:**
**Checklist:**
> Notification - Send notification when direct assignment during creation of request

- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/AssignedDepartmentHandler.cs
- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/NotifyRequestCreatorHandler.cs
- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/NotifyResourceOwnerHandler.cs
- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/NotifyTaskOwnerHandler.cs
- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/ProposedPersonHandler.cs
PRO-ORG app uri, uses project identifier, and not context identifier.
Replace to ensure working link.
Fixed funky variable names too.
**Testing:**
**Checklist:**
> Notification - PRO-ORG identifier

- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/NotifyRequestCreatorHandler.cs
- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/NotifyResourceOwnerHandler.cs
- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/NotifyTaskOwnerHandler.cs
- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/RequestInitializedHandler.cs
Adjust headers. Should contain more info in mail header.
Adjusted card for requestinitialized too.
**Testing:**
**Checklist:**
> Notification - Mail and card header adjustments

- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/CreateResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Personnel/SearchPersonnel.cs
- src/backend/api/Fusion.Resources.Domain/Utils/PeopleSearchUtils.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
> Add endpoint to search personnel

- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/AssignedDepartmentHandler.cs
- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/ProposedPersonHandler.cs
- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/RequestInitializedHandler.cs
Added request number and position id to notification card facts if value exists.
**Testing:**
Tests triggering notifications verified
**Checklist:**
>  Notifications - Extra facts in cards

- src/backend/api/Fusion.Resources.Api/Startup.cs
- src/backend/api/Fusion.Resources.Domain/Services/IRequestRouter.cs
- src/backend/api/Fusion.Resources.Domain/Services/RequestRouter.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Queries/ResolveResponsibleDepartment.cs
- src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/UnassignedRequests/DepartmentUnassignedTests.cs
- src/backend/tests/Fusion.Resources.Logic.Tests/RequestAssignment.cs
Fallback to base position department when routing requests.
**Testing:**
**Checklist:**
> Fallback to base position when attempting to assign request

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/CanApproveStepHandler.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/DirectAllocationRequestStarted.cs
- src/backend/api/Fusion.Resources.Logic/Workflows/AllocationDirectWorkflowV1.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Requests/ApiCreateInternalRequestModel.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/DirectRequestTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationNotificationTests.cs
The direct request workflow should be similar to normal workflow.
Difference is that it should require an assigned department and a proposed person before starting request
**Testing:**
Created new tests covering direct request workflow
**Checklist:**
> AllocationRequest workflow - Direct workflow adjustments

- src/backend/api/Fusion.Resources.Domain/Models/QueryInternalPersonnelPerson.cs
- src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentPersonnel.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetSectorPersonnel.cs
- src/backend/api/Fusion.Resources.Domain/Utils/PeopleSearchUtils.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
- src/backend/tests/Fusion.Testing.Mocks.ProfileService/Api/PersonsController.cs
Change how external hires under manager in department are filtered out.
**Testing:**
**Checklist:**
> Include correct personnel in timeline/list view

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Requests/InternalRequests/ResetWorkflow.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
Add endpoint to reset state and workflow when sending request back to task owner.
**Testing:**
**Checklist:**
> Reset allocation state/workflow for request

- src/backend/api/Fusion.Resources.Domain/Commands/Departments/GetRelevantDepartments.cs
- src/backend/api/Fusion.Resources.Domain/Services/RequestRouter.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/DirectAllocationRequestStarted.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Requests/ApiCreateInternalRequestModel.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/DirectRequestTests.cs
- src/backend/tests/Fusion.Resources.Logic.Tests/RequestAssignment.cs
Direct requests should be assigned to the proposed persons department.
**Testing:**
**Checklist:**
> Assign dept when person is proposed

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiRequestConversationMessage.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/ConversationsController.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/AddRequestConversationMessageRequest.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/UpdateRequestConversationMessage.cs
- src/backend/api/Fusion.Resources.Api/EnumExtensions.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbConversationMessage.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20210708103448_add_request_conversations.Designer.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20210708103448_add_request_conversations.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20210709123024_add_request_conversation.Designer.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20210709123024_add_request_conversation.cs
- src/backend/api/Fusion.Resources.Database/Migrations/ResourcesDbContextModelSnapshot.cs
- src/backend/api/Fusion.Resources.Database/ResourcesDbContext.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Conversations/AddRequestConversationMessage.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Conversations/GetRequestConversation.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Conversations/GetRequestConversationMessage.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Conversations/UpdateRequestConversationMessage.cs
- src/backend/api/Fusion.Resources.Domain/Extensions/EnumMappingExtensions.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryConversationMessage.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiRequestMessage.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestConversationTests.cs
As described in https://github.com/equinor/fusion/pull/108/files?short_path=3651bf1#diff-3651bf19d4481f8b35676b13cc20ce0fceab59f6da5d465bb741c82461a7e093
**Testing:**
**Checklist:**
> Add conversations to requests

- .github/workflows/js-build.yml
- .github/workflows/test-api.yml
- src/frontend/package.json
- src/frontend/src/api/ApiClient.ts
- src/frontend/src/components/AdStatusIcon.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelMailsPage/usePersonnelContactMail.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/useContractPageNavigationStructure.tsx
Fixed typo in meny and updated methods with correct spelling.
Bumped patch version.
**Testing:**
n/a
**Checklist:**
> App - Fixed preffered typo to preferred

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Tasks/GetMultipleRequestTasks.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Tasks/GetTasksForRequests.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequestItem.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestConversationTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestTaskTests.cs
Enable expanding tasks/conversations on single requests itemsEnable expanding tasks/conversations on single requests items
**Testing:**
**Checklist:**
> Enable expanding tasks/conversations on single requests items

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Departments/DeleteDelegatedResourceOwner.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsController.cs
Add endpoint to delete delegated resource owners
**Testing:**
**Checklist:**
> Add endpoint to remove delegated resource owner

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsController.cs
Resolve [AB#21592](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/21592)
**Testing:**
**Checklist:**
> Include department for position related endpoint

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/RequestActionsController.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbRequestAction.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Tasks/DeleteRequestAction.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryResourceAllocationRequest.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequestItem.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/ResourceOwnerRequestTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestActionTests.cs
> prevent starting requests with unresolved required actions

- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
- src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentPersonnel.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiPersonnelPerson.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
- src/backend/tests/Fusion.Testing.Mocks.ProfileService/Api/PersonsController.cs
- src/backend/tests/Fusion.Testing.Mocks.ProfileService/Fusion.Testing.Mocks.ProfileService.csproj
- src/backend/tests/Fusion.Testing.Mocks.ProfileService/PeopleServiceMock.cs
This reverts commit 55fb88de31d429d22da98cffc3ee0d28065f5296.
> Revert "Hide past allocations in timeline (#377)"

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/RequestActionsController.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Tasks/GetRequestActions.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestActionTests.cs
Add filters for request source, responsible and type for request actions.
**Testing:**
**Checklist:**
> Add filters for request actions

- src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
- src/backend/api/Fusion.Resources.Application/Fusion.Resources.Application.csproj
- src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
- src/backend/api/Fusion.Resources.Domain/Services/RequestRouter.cs
- src/backend/function/Fusion.Resources.Functions/Fusion.Resources.Functions.csproj
- src/backend/tests/Fusion.Resources.Api.Tests/FusionMocks/EventNotificationClientMock.cs
- src/backend/tests/Fusion.Testing.Authentication/Fusion.Testing.Authentication.csproj
- src/backend/tests/Fusion.Testing.Mocks.ContextService/Fusion.Testing.Mocks.ContextService.csproj
- src/backend/tests/Fusion.Testing.Mocks.LineOrgService/Fusion.Testing.Mocks.LineOrgService.csproj
- src/backend/tests/Fusion.Testing.Mocks.OrgService/Fusion.Testing.Mocks.OrgService.csproj
- src/backend/tests/Fusion.Testing.Mocks.ProfileService/Api/PersonsController.cs
- src/backend/tests/Fusion.Testing.Mocks.ProfileService/Fusion.Testing.Mocks.ProfileService.csproj
Update fusion libs to get fix for resource owner cache problems
**Testing:**
**Checklist:**
> Update & consolidate fusion libraries

- src/backend/api/Fusion.Resources.Api/Controllers/ApiModels/ApiPerson.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiRequestAction.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Tasks/AddRequestAction.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Tasks/GetActionsForRequests.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Tasks/GetRequestAction.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Tasks/GetRequestActions.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Tasks/QueryRequestAction.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Tasks/UpdateRequestAction.cs
- src/backend/api/Fusion.Resources.Domain/Utils/RequestActionExtensions.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiPerson.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestActionTests.cs
- Fix bug where patching could unset `assignedTo`.
- Resolve full profiles for persons related to action.
**Testing:**
**Checklist:**
> Request action improvements part 2

- src/backend/api/Fusion.Resources.Domain/Services/RequestRouter.cs
- src/backend/tests/Fusion.Resources.Logic.Tests/RequestAssignment.cs
Fixes a bug where irrelevant routes are matched . [AB#22452](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/22452)
**Testing:**
**Checklist:**
> Do not score irrelevant rules in routing

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Approve.cs
- src/backend/api/Fusion.Resources.Logic/Workflows/Base/WorkflowDefinition.cs
.../approve endpoint using department route was not sending notifications.
Move publishing of notification message from controller and into approval command.
[AB#22519](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/22519)
**Testing:**
**Checklist:**
> API - Notification not sent to creator of request during approval

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/AnalyticsController.cs
Make swagger great again.
Remove duplicate api-model causing swagger issue.
Reuse ApiAbsenceType model in AnalyticsController (from ApiPersonAbsence.ApiAbsenceType)
https://resources-api-pr-426.fusion-dev.net/swagger
**Testing:**
**Checklist:**
> API - Swagger crash

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/ContractAdminTable/columns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/ContractAdminTable/styles.less
Check if valid to date is overdue in delegate access table.
If the date is overdue, it will show "Overdue" instead of "x days left"
> fix: check for overdue valid to date

- docs/contract-management.md
Fixed incorrect url for placeholder images
> Updated docs to fix image placeholder

- src/backend/api/Fusion.Resources.Domain/Extensions/FusionPersonProfileExtensions.cs
- src/backend/api/Fusion.Resources.Domain/Services/ProfileServices.cs
- src/backend/function/Fusion.Resources.Functions/Functions/ProfileSync.cs
* Should process all users. Existing function limits to max 1000 accounts. Build collection based on skip/take
* Ensure users with azure id is considered available when invitation status is missing.
[AB#24244](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/24244)
**Testing:**
**Checklist:**
> AzFunc - ProfileSync

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/columns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelMailsPage/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ProvisioningRequestsPage/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/styles.less
- Make sure only table scrolls, not entire page
- Added warning  icon to actual mpp page of overdue or soon overdue 
NOTE: Use fusion-components version of warning icon. Tried with fusion react icon, but got error.
Use fusion comp version for now due to the high propriety of this pr
> fix: table scroll fix and overdue icon

- src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentPersonnel.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
Now filters away completed requests from pending requests when fetching timeline data
**Testing:**
**Checklist:**
> Completed requests included in timeline pending requests

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
* Added missing await statement to option endpoints for checking approval access.
* Removed unused variable usage.
* Added missing xml comment.
[AB#25113](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/25113)
**Testing:**
**Checklist:**
> API - Internal Requests - Missing await

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryWorkflow.cs
Current implementation didn't send next step to CanApproveStep check in the option endpoints for requests.
NextStep is required, and bugfix ensures next step to be sent.
[AB#25158](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/25158)
**Testing:**
Tested request locally using postman
**Checklist:**
> API - Internal Requests - Options request failure

- src/backend/api/Fusion.Resources.Api/Configuration/DatabaseConfigurationExtensions.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiContractPersonnel.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiExternalPersonnelPerson.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbExternalPersonnelPerson.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20220112143008_ExternalPersonnel UPN property added.Designer.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20220112143008_ExternalPersonnel UPN property added.cs
- src/backend/api/Fusion.Resources.Database/Migrations/ResourcesDbContextModelSnapshot.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Personnel/CreateContractPersonnel.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryContractPersonnel.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryExternalPersonnelPerson.cs
- src/backend/api/Fusion.Resources.Domain/Services/IProfileServices.cs
- src/backend/api/Fusion.Resources.Domain/Services/ProfileServices.cs
- src/backend/tests/Fusion.Resources.Domain.Tests/PersonnelCommandTests.cs
* Added UPN property to DBExternalPersonnel
* Added UPN to query models (QueryContractPersonnel/QueryExternalPersonnelPerson)
* Added UPN to api models (ApiContractPersonnel/ApiExternalPersonnelPerson)
* Added UPN to be updated during profile refresh
[AB#25128](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/25128)
**Testing:**
**Checklist:**
> API - ExternalPersonnel UPN property added

- src/backend/api/Fusion.Resources.Domain/Services/ProfileServices.cs
At the moment new accounts is not having azureUniqueId set.
This results in new accounts never to be activated.
Introduced when expecting azureUniqueId to be same in people and external personnel.
Did not think of new accounts
[AB#25815](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/25815) 
**Testing:**
Hard to test. Tried using azure/api.
**Checklist:**
> API - ProfileService - Refresh new account issue

- src/backend/api/Fusion.Resources.Api/Controllers/ResponsibilityMatrix/ResponsibilityMatrixController.cs
- fixes [AB#25852](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/25852)
allow both Fusion.Resources.FullControl and Fusion.Resources.Internal.FullControl roles access to request routing
**Testing:**
**Checklist:**
> allow both Fusion.Resources.FullControl and Fusion.Resources.Internal.FullControl roles access to request routing

- docs/contract-management.md
- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/api/ApiClient.ts
- src/frontend/src/api/ResourceCollection.ts
- src/frontend/src/models/ReplacePersonRequest.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelColumns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/DeletedAccountInfo.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/useReplacePersonAccess.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/ReplaceUserSideSheet/ReplaceUserSideSheetContent.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/ReplaceUserSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/ReplaceUserSideSheet/styles.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/ReplaceUserSideSheet/useCheckForUpdatedPerson.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/ReplaceUserSideSheet/useUpdatePerson.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/components/RadioFilter/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/styles.less
[Docs](https://docs.fusion-dev.net/domain/apps/external-personnel/tech-spec/handle-deleted-profiles/)
> Frontend -  Handle deleted accounts

- docs/contract-management.md
- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/api/ApiClient.ts
- src/frontend/src/api/ResourceCollection.ts
- src/frontend/src/models/Personnel.ts
- src/frontend/src/models/PositionWithPersonnel.ts
- src/frontend/src/models/ReplacePersonRequest.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/AzureAdStatusIndicator/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditablePositionDetails/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/components/RequestDetailsSideSheet/CompactPersonDetails.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/columns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/getFilterSections.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelMailsPage/PersonnelMailsTable/getColumns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelColumns.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/DeletedAccountInfo.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/styles.less
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/useReplacePersonAccess.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/ReplaceUserSideSheet/ReplaceUserSideSheetContent.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/ReplaceUserSideSheet/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/ReplaceUserSideSheet/styles.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/ReplaceUserSideSheet/useCheckForUpdatedPerson.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/ReplaceUserSideSheet/useUpdatePerson.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/components/RadioFilter/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/getFilterSections.ts
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/index.tsx
- src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/styles.less
added ad status in manage mpp table and filter
> Frontend - Added ad status in manage mpp table and filter

- pipelines/api-pipeline.yml
- pipelines/api-pr-pipeline.yml
- pipelines/environment-pipeline.yml
- pipelines/function-pipeline.yml
- pipelines/function-pr-pipeline.yml
- pipelines/fusion-app-pipeline.yml
- pipelines/pr-cleanup-pipeline.yml
- src/backend/api/Fusion.Resources.Domain/Extensions/FusionPersonProfileExtensions.cs
During profile synchronization, invalid AccountStatus observed for deleted/expired accounts.
Extension fetching DbAccountStatus should consider IsExpired flag during profile refresh.
If IsExpired (from People Service), should return NoAccount instead of Available.
[AB#26250](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/26250)
**Testing:**
Tested refresh locally using postman
**Checklist:**
> API - ProfileSync - Invalid AccountStatus observed

- src/backend/infrastructure/grant-adapp-sql-access.ps1
SQL server module not installed by default.
Build pipeline fails due to missing module.
Ensure module is being installed before imported by powershell script
**Testing:**
**Checklist:**
> INFRA - SQL Access - Powershell issue

- pipelines/templates/deploy-function-template.yml
- src/backend/infrastructure/cleanup-secrets.ps1
* Remove force param from cleanup
* Ensure version is removed from keyvault references. Should use latest and greatest
**Testing:**
**Checklist:**
> Build pipeline bugfixes

- pipelines/templates/deploy-function-template.yml
* Should make sure the keyvault references in config is created without version
**Testing:**
**Checklist:**
> Pipeline - Secrets without version

- src/backend/api/Fusion.Resources.Api/Authentication/SharedRequestClaimsTransformation.cs
- src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
- src/backend/api/Fusion.Resources.Api/Authorization/ResourcesClaimTypes.cs
- src/backend/api/Fusion.Resources.Api/Controllers/ApiModels/RequestReferences/PersonReference.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/ShareRequestRequest.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/ShareRequestsController.cs
- src/backend/api/Fusion.Resources.Api/Startup.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbSharedRequest.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20220516095453_add_shared_requests.Designer.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20220516095453_add_shared_requests.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20220519110718_add_rq_sharing_index.Designer.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20220519110718_add_rq_sharing_index.cs
- src/backend/api/Fusion.Resources.Database/ResourcesDbContext.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Requests/Sharing/RevokeShareRequest.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Requests/Sharing/ShareRequest.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Requests/Sharing/SharedRequestSource.cs
- src/backend/api/Fusion.Resources.Domain/Models/QuerySharedRequest.cs
- src/backend/api/Fusion.Resources.Domain/Models/SharedRequestScopes.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequestItem.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
- src/backend/api/Fusion.Resources.Domain/Services/IProfileServices.cs
- src/backend/api/Fusion.Resources.Domain/Services/ProfileServices.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/SharedRequestTests.cs
- src/backend/tests/Fusion.Testing.Mocks.LineOrgService/Api/Models/ApiModels.cs
Allow sharing requests with users without normal privileges in line org/project org.
https://docs.fusion-dev.net/pr-194/domain/services/resources/tech-specs/ote-second-opinion/
**Testing:**
**Checklist:**
> Add sharing of requests

- src/backend/api/Fusion.Resources.Domain/Commands/SecondOpinions/AddSecondOpinion.cs
- src/backend/tests/Fusion.Resources.Domain.Tests/Fusion.Resources.Domain.Tests.csproj
- src/backend/tests/Fusion.Resources.Domain.Tests/NotificationTests.cs
- src/backend/tests/Fusion.Resources.Logic.Tests/RequestAssignment.cs
- src/backend/tests/Fusion.Resources.Test.Core/DbTestFixture.cs
- src/backend/tests/Fusion.Resources.Test.Core/Fusion.Resources.Test.Core.csproj
AB#30587
**Testing:**
**Checklist:**
> Ensure second opinion id is known before sending notification

- pipelines/api-pipeline.yml
- pipelines/environment-pipeline.yml
- pipelines/function-pipeline.yml
- pipelines/fusion-app-pipeline.yml
- pipelines/secret-rotation-pipeline.yml
- src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestNotification/SecondOpinionNotificationHandler.cs
Add TR environment for RESOURCES APP
**Testing:**
**Checklist:**
> PIPELINE - TR Environment

- src/backend/api/Fusion.Resources.Api/Program.cs
To be able to override appsettings we introduce an optional jsonfile to be used if wanted.
Added as a json file, using optional flag.
**Testing:**
**Checklist:**
> API - Add support for an additional but optional appsettings.json

- src/backend/function/Fusion.Resources.Functions/Deployment/function.template.json
Missing endpoint configurations added to arm-template.
Include location property missing.
**Testing:**
**Checklist:**
> CHORE - Function template - Ensure all endpoints used are mapped in arm template

- src/backend/function/Fusion.Resources.Functions/local.settings.template.json
Change/fix/update in local dev-config/template.
No risk/relevance for production code.
**Testing:**
**Checklist:**
> CHORE - Backend Configuration fix

- pipelines/api-pipeline.yml
> api-pipeline.yml pipeline - add missing template param

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/AddDelegatedResourceOwnerRequest.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbDelegatedDepartmentResponsible.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20230103180113_DelegatedDepartmentResponsibles table added.Designer.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20230103180113_DelegatedDepartmentResponsibles table added.cs
- src/backend/api/Fusion.Resources.Database/ResourcesDbContext.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Departments/AddDelegatedResourceOwner.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Departments/DeleteDelegatedResourceOwner.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Requests/InternalRequests/DeleteInternalRequest.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryDepartmentResponsible.cs
- src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartment.cs
- src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentHandlerBase.cs
- src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartments.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceOwnerProfile.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourceApiFixture.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs
- src/backend/tests/Fusion.Testing.Core/TestDbConnectionStrings.cs
Re-introducing table for persisting delegated department repsonsibility.
**Testing:**
**Checklist:**
> Delegated Department Responsibles table added

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
- src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/TestClientHttpResponseExtensions.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs
* New endpoint to be used for access check (OPTIONS) when delegating resource owners.
* Added tests
* [AB#34952](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/34952)
**Testing:**
**Checklist:**
> Options endpoint to be used requesting /departments/{departmentId}/delegated-resource-owners

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
Delegated resource owners endpoints should be allowed to access by resource owners, and people being delegated resource owner roles. Not just admins as today.
**Testing:**
**Checklist:**
> Adjust and align authorization rules for endpoints related delegated resource owners

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/ApiRelevantOrgUnit.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonController.cs
- src/backend/api/Fusion.Resources.Api/FusionEvents/LineOrgOrgUnitChangedEvent.cs
- src/backend/api/Fusion.Resources.Domain/Configuration/IServiceCollectionExtensions.cs
- src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
- src/backend/api/Fusion.Resources.Domain/Models/QueryOrgUnitReason.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryRangedList.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryRelevantOrgUnit.cs
- src/backend/api/Fusion.Resources.Domain/Queries/GetRelevantOrgUnits.cs
- src/backend/api/Fusion.Resources.Domain/ReasonRoles.cs
- src/backend/api/Fusion.Resources.Domain/Services/IOrgUnitCache.cs
- src/backend/api/Fusion.Resources.Domain/Services/OrgUnitCache.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourcesApiWebAppFactory.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Responses/TestApiRelevantOrgUnitModel.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonControllerTests.cs
- src/backend/tests/Fusion.Testing.Core/IServiceCollectionExtensions.cs
- src/backend/tests/Fusion.Testing.Mocks.LineOrgService/Api/OrgUnitController.cs
- src/backend/tests/Fusion.Testing.Mocks.LineOrgService/LineOrgServiceMock.cs
Created a api endpoint to enable query for relevant deparment context data for the active user.
[AB#33286](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33286)
**Testing:**
**Checklist:**
> Context-search-relevant-departmnet-endpoint

- src/backend/api/Fusion.Resources.Api/HostedServices/ExpiredDelegatedRolesHostedService.cs
- src/backend/api/Fusion.Resources.Api/Startup.cs
- src/backend/api/Fusion.Resources.Database/Entities/DbDelegatedDepartmentResponsibleHistory.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20230214083153_DelegatedDepartmentResponsibleHistory.Designer.cs
- src/backend/api/Fusion.Resources.Database/Migrations/20230214083153_DelegatedDepartmentResponsibleHistory.cs
- src/backend/api/Fusion.Resources.Database/ResourcesDbContext.cs
- src/backend/tests/Fusion.Resources.Api.Tests/ExpiredDelegatedRolesHostedServiceTests.cs
New hosted service running periodically and moving expired delegated department responsible data to history table.
[AB#36134](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/36134)
**Testing:**
**Checklist:**
> API HostedService - Expired delegated department responsibility cleanup

- pipelines/templates/deploy-function-template.yml
Added a if statement to set production to us App Service and not K8 link
**Testing:**
**Checklist:**
#AB33091
> Updated DeploymentTemplate to use App Service instead of K8

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
- src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourceApiFixture.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonControllerTests.cs
- src/backend/tests/Fusion.Testing.Core/Assertion/TestClientHttpResponseAssertions.cs
A person been delegated responsible for a department, should not be allowed to re-delegate their role
[AB#36271](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/36271)
**Testing:**
**Checklist:**
> API - Delegated resource owners should not have access to delegate role as resourceowner they have been delegated

- src/backend/Fusion.Resources.Authorization/Handlers/CanDelegateAccessToDepartmentHandler.cs
- src/backend/Fusion.Resources.Authorization/Requirements/CanDelegateAccessToDepartmentRequirement.cs
- src/backend/api/Fusion.Resources.Api/Authentication/ResourcesLocalClaimsTransformation.cs
- src/backend/api/Fusion.Resources.Api/Authorization/Extensions/AuthorizationConfigurationExtensions.cs
- src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
- src/backend/api/Fusion.Resources.Api/Startup.cs
- src/backend/api/Fusion.Resources.Domain/Authorization/ResourcesClaimTypes.cs
- src/backend/api/Fusion.Resources.Domain/Utils/DepartmentPath.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs
- src/backend/tests/Fusion.Testing.Mocks.ProfileService/PeopleServiceMock.cs
As a resource owner you should have access to delegate responsibility to own and descendant departments.
[AB#36427](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/36427)
**Testing:**
Should be able to test as resource owner.
Integration tests created and verified
**Checklist:**
> Delegate Responsibility - Can delegate to own and descendant departments as resource owner

- pipelines/pr-cleanup-pipeline.yml
Update service-connection
**Testing:**
**Checklist:**
> fix(aks): Update service-connection

- src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentPersonnel.cs
The manager filter have been readded as it did not work as inteded. 
Previous pr is :  Removed manager filter #412
[AB#41694](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/41694)
**Testing:**
AB#
**Checklist:**
> fix: Re add manager filter

- src/backend/api/Fusion.Resources.Api/FusionEvents/Handlers/InternalRequests/RequestUpdatedHandler .cs
- src/backend/integration/Fusion.Resources.Integration.Models/FusionEvents/EventType.cs
Created RequestUpdateHandler (based on RequestCreatedHandler) for sending out events when a request is updated. It is related to clearing cache for Orphaned Requests in FRA Application Management.
**Testing:**
You need to subscribe for events from the resource-API of type ResourceAllocationRequestSubscriptionEvent and where the EventType is RequestUpdated.
[AB#42635](https://statoil-proview.visualstudio.com/Fusion%20Resource%20Allocation/_workitems/edit/42635)
**Checklist:**
> Added RequestUpdateHandler

- src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
> fix:Changed position for ResourcesReadRole

- src/backend/function/Fusion.Resources.Functions/ApiClients/LineOrgApiClient.cs
API call to the lineorg-api got faulty query due to Linq aggregate not working as intended, fixed with workaround.
**Testing:**
**Checklist:**
> (fix)functions: Lineorg client bug

- pipelines/templates/deploy-function-pr-template.yml
- pipelines/templates/deploy-function-template.yml
- src/backend/function/Fusion.Resources.Functions/ApiClients/LineOrgApiClient.cs
- src/backend/function/Fusion.Resources.Functions/Deployment/function.template.json
The notification que was added to the application config.
**Testing:**
**Checklist:**
> (fix)functions: Notification queue added to config

- src/backend/function/Fusion.Resources.Functions/ApiClients/LineOrgApiClient.cs
- src/backend/function/Fusion.Resources.Functions/ApiClients/NotificationApiClient.cs
- src/backend/function/Fusion.Resources.Functions/ApiClients/PeopleApiClient.cs
- src/backend/function/Fusion.Resources.Functions/ApiClients/ResourcesApiClient.cs
Some of the apicalls timed out after 100 sec. Solved by extending the api-client timeout to five minuets. 
**Testing:**
**Checklist:**
> (fix)Functions: API client timeout

- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/Models/AdaptiveCards/AdaptiveCardBuilder.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ScheduledReportContentBuilderFunction.cs
The point "Project changes affecting next 3 months" has been changed to "Project changes last week affecting next 3 months" and will only contain changes that have been done the last week (7 days). 
And the calculation of FindTotalCapacityIncludingLeave has been changed
**Testing:**
**Checklist:**
> Adjusting "Project changes last week affecting next 3 months"

- src/backend/function/Fusion.Resources.Functions/ApiClients/OrgApiClient.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/AdaptiveCardBuilder.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/Models/AdaptiveCards/AdaptiveCardBuilder.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/Models/AdaptiveCards/ResourceOwnerAdaptiveCardData.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/Models/PersonnelContent.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ScheduledReportContentBuilderFunction.cs
- src/backend/function/Fusion.Resources.Functions/host.json
- Code cleanup.
- Some rewrite of the adaptive card builder.
- API calls made async.
- Lists of API calls is now processed in multiple threads.
- Function-timeout period change from 5 to 10 min.
**Testing:**
**Checklist:**
> chore(function): Cleanup and performance upgrade on notifications

- src/backend/function/Fusion.Resources.Functions/ApiClients/IOrgApiClient.cs
- src/backend/function/Fusion.Resources.Functions/ApiClients/OrgApiClient.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ScheduledReportContentBuilderFunction.cs
CHanged the way we get and loop through change-log events for when building notifications.
**Testing:**
Start function scheduled-notification
**Checklist:**
> fix: Scheduled notifications: Adjusted getting change-log

- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ResourceOwnerReportDataCreator.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ScheduledReportContentBuilderFunction.cs
> (fix)function: Average time to handle request update

- src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentRequestsTimeline.cs
When getting requests via /departments/{departmentString}/resources/requests/timeline we try to resolve all referenced Positions by checking the OrgPositionId. Because the request may reference deleted positions this may result in 404 in the Org-API. Some endpoints in Resource-API is returning alot of requests and this may also result in many 404s in Org-API. To avoid this we cache all OrgPositionId which returns 404 and don't check them again. 
The timeout for cache has been set to 7 days.
WorkItem:
[AB#44789](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/44789)
Related pr: 
https://github.com/equinor/fusion-app-resources/pull/624
**Testing:**
Not that easy to test as this is to reduce the errors in application …
> feat/Add cache of positionIds not found when getting requests (timeline)

- pipelines/templates/replace-tokens.yml
- src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
Updating replaceTokens from verison 3 to version 6
[AB#52480](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/52480)
**Testing:**
**Checklist:**
> feature(resource): updated replaceTokens in yml-file to version 6

- src/Fusion.Resources.Functions.Common/ApiClients/ISummaryApiClient.cs
- src/Fusion.Resources.Functions.Common/ApiClients/SummaryApiClient.cs
- src/Fusion.Summary.Functions/CardBuilder/AdaptiveCardBuilder.cs
- src/Fusion.Summary.Functions/Deployment/disabled-functions.json
- src/Fusion.Summary.Functions/Functions/DepartmentResourceOwnerSync.cs
- src/Fusion.Summary.Functions/Functions/WeeklyReportSender.cs
This adds the Azure function that will retrieve the weekly reports from the api summary, build the notification and send it. Function is disabled as the summary api is not running.
[AB#51134](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/51134)
**Testing:**
**Checklist:**
> feat: AZ func Weekly report sender

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
This will enable functions to implement this endpoint
**Expected result**: Trusted applications (functions and other) will be allowed to poll this endpoint
**Checklist**:
> Fix: Added access policy to endpoint

- src/Fusion.Resources.Functions.Common/ApiClients/IResourcesApiClient.cs
- src/Fusion.Resources.Functions.Common/ApiClients/LineOrgApiClient.cs
- src/Fusion.Resources.Functions.Common/ApiClients/ResourcesApiClient.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/DTOs/ScheduledNotificationQueueDto.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ScheduledReportContentBuilderFunction.cs
- src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ScheduledReportTimerTriggerFunction.cs
We found out that we could expand LineOrg call to include the recipients so we can drop the extra call resolving notification recipients.
**Expected result**: A more effective function
Link to workitem: [LINK](https://statoil-proview.visualstudio.com/Fusion%20Resource%20Allocation/_workitems/edit/54652)
**Checklist**:
> Feat: Update with expanded LineOrg API

- pipelines/templates/deploy-container-app.yml
- pipelines/templates/deploy-function-pr-template.yml
- pipelines/templates/deploy-function-template.yml
Updated version of azurepowershell task to V5, as this support federated credentials.
**Testing:**
Verfied running pipeline on branch.
**Checklist:**
> chore(pipeline): Fix function pipeline

- src/Fusion.Resources.Functions.Common/Fusion.Resources.Functions.Common.csproj
- src/Fusion.Summary.Functions/Fusion.Summary.Functions.csproj
- src/backend/function/Fusion.Resources.Functions/Fusion.Resources.Functions.csproj
- src/backend/tests/Fusion.Resources.Functions.Tests/Fusion.Resources.Functions.Tests.csproj
[AB#55664](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/55664)
This updates the Azure function apps to .net 8, this also means all packages were updated to the latest version.
I also removed some duplicate and unnecessary package references.
**Testing:**
I did some simple testing like checking that the functions started.
**Checklist:**
> chore: Update azure functions to .net8

- src/Fusion.Resources.Functions.Common/Fusion.Resources.Functions.Common.csproj
- src/Fusion.Summary.Functions/Deployment/function.template.json
- src/Fusion.Summary.Functions/Fusion.Summary.Functions.csproj
- src/backend/function/Fusion.Resources.Functions/Deployment/function.template.json
- src/backend/function/Fusion.Resources.Functions/Fusion.Resources.Functions.csproj
- src/backend/function/Fusion.Resources.Functions/Startup.cs
Azure functions crashed due to missing the package Microsoft.Extensions.Configuration.Abstractions and missing some additional setting changes
> Added Microsoft.Extensions.Configuration.Abstractions

- infrastructure/arm/environment.template.json
- pipelines/summary-function-pipeline.yml
- pipelines/summary-function-pr-pipeline.yml
- pipelines/templates/deploy-summary-function-pr-template.yml
- pipelines/templates/deploy-summary-function-template.yml
- src/Fusion.Summary.Functions/Startup.cs
[AB#55574](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/55574)
Creates a deployment pipeline for the summary function app. Also updates the existing summary PR function.
**Testing:**
Will need to run the infra pipeline to deploy the function app in ci->
**Checklist:**
> chore: Update summary function app pipelines

- pipelines/templates/deploy-summary-function-template.yml
Only updated deploy PR template and forgot to update the actual deployment template.
> chore: Added missing departmentFilter setting in deployment pipeline

- src/tests/Fusion.Summary.Api.Tests/IntegrationTests/SummaryReportTests.cs
Due to a code typo a summary test started to fail on Mondays.
**Testing:**
**Checklist:**
> fix(summary): Fixes code typo where summary test fails on monday

- pipelines/summary-api-pipeline.yml
- pipelines/templates/deploy-summary-container-app.yml
- src/Fusion.Summary.Api/Deployment/webapp.template.json
- src/Fusion.Summary.Functions/Deployment/disabled-functions.json
[AB#55224](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/55224)
Adds prod deployment template
Disables new az functions
Fixed minor typo in deployment script
**Testing:**
Summary Api and az functions have been deployed to production with this PR.
**Checklist:**
> chore: Create Summary prod deployment container template

- src/Fusion.Resources.Functions.Common/ApiClients/ISummaryApiClient.cs
- src/Fusion.Resources.Functions.Common/ApiClients/SummaryApiClient.cs
- src/Fusion.Resources.Functions.Common/Extensions/HttpResponseMessageExtensions.cs
- src/Fusion.Summary.Functions/Functions/WeeklyDepartmentSummaryWorker.cs
Failed api calls will now throw an exception instead of silently returning. If a worker fails to process a report it will no longer complete the message.
**Testing:**
**Checklist:**
> chore(summary): Error handling adjustments

- src/Fusion.Summary.Functions/Deployment/disabled-functions.json
- src/backend/function/Fusion.Resources.Functions/Deployment/disabled-functions.json
> chore(summary): Enable new summary az funcs and disable old ones

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
Fixed correct property to use when searching for resource owner
[AB#56436](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/56436)
**Testing:**
**Checklist:**
> fix: delete delegated resource owner

- src/Fusion.Summary.Api/Deployment/k8s/deployment-ingress-prod.yml
- src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-ingress-prod.yml
Incorrect equinor dns used in ingress. Changed to correct sub dns.
**Testing:**
Not in use yet, will verify when deployed.
**Checklist:**
> fix(pipelines): Fixed incorrect equinor dns for aks services

- src/Fusion.Summary.Api/Deployment/k8s/deployment-service.yml
- src/Fusion.Summary.Api/Deployment/k8s/pr-deployment-env.yml
- src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-service.yml
- src/backend/api/Fusion.Resources.Api/Deployment/k8s/pr-deployment-env.yml
Isolated k8s config manifest files to each application to prevent them overwriting eachother.
**Testing:**
Should inspect CI to see that the api is working and can load secret/config as expected
**Checklist:**
> fix: Isolated k8s config files

- CONTRIBUTING.md
- SECURITY.md
Added missing files that describes how to contribute and how to report security issues
**Testing:**
No code changes, no need to test
**Checklist:**
> Added missing files

- pipelines/templates/deploy-summary-function-template.yml
**Testing:**
Tested by running ci pipeline
**Checklist:**
> fix(summary): Remove extra ' " '

- src/Fusion.Summary.Api/Deployment/k8s/deployment-ingress-prod.yml
- src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-ingress-prod.yml
Updated ingress class name
**Testing:**
**Checklist:**
> chore(k8s): Updated ingress class name in prod

- pipelines/api-pr-pipeline.yml
- pipelines/summary-api-pr-pipeline.yml
- src/Fusion.Summary.Api/appsettings.json
- src/backend/api/Fusion.Resources.Api/appsettings.json
Fusion infra wanted pr images to be pushed to the sandbox container registry.
Changed container registry used for pr pipelines.
**Testing:**
**Checklist:**
> chore: Change to sandbox container registry for PR

- src/Fusion.Resources.Functions.Common/ApiClients/ResourcesApiClient.cs
- src/Fusion.Summary.Functions/Functions/TaskOwnerReports/WeeklyTaskOwnerReportWorker.cs
- src/Fusion.Summary.Functions/ReportCreator/WeeklyTaskOwnerReportDataCreator.cs
- src/tests/Fusion.Summary.Functions.Tests/Notifications/WeeklyTaskOwnerReportDataCreator.cs
We don't want to show TBN positions with an allocation request.
**Testing:**
Tested locally and in CI
**Checklist:**
> feat(summary): Filter out tbn positions with requests

- pipelines/pr-cleanup-pipeline.yml
Comments out the steps that involve removing aks resources. 
Deployments have time to live set to 7, Core wants to add a webhook to have more granular control of what can be deleted in the cluster
**Testing:**
**Checklist:**
> chore: Comment out deletion of aks resources

- src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-service.yml
Increased number of replicas
**Testing:**
**Checklist:**
> chore(k8s): Increase replicas

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
Was missing validation that the position was in the project.
**Testing:**
**Checklist:**
> fix(resources): Ensure position belongs to project

- src/backend/api/Fusion.Resources.Domain/Queries/GetResourceOwnerProfile.cs
Fixed inaccuracy in the comment explaining ResolveDelegatedResponsibilities
**Testing:**
**Checklist:**
> fix: comment for ResolveDelegatedResponsibilities

- .github/dependabot.yml
> chore: Updated dependabot config

- src/Fusion.Summary.Api/Domain/Queries/GetWeeklySummaryReportsMetaData.cs
Added possibility to sort and filter on weekly summary report metadata. 
**Testing:**
**Checklist:**
> feat(summary): sort and filter weekly summary reports metadata

- src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/ApiRelatedDepartments.cs
- src/backend/api/Fusion.Resources.Domain/Commands/Departments/GetRelatedDepartments.cs
- src/backend/api/Fusion.Resources.Domain/Models/QueryRelatedDepartments.cs
- src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs
Work Item: [AB#63096](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/63096)
Added the parent department to the result from the related departments endpoint.
**Testing:**
**Checklist:**
> feat: add parent to related departments endpoint

- src/Fusion.Summary.Api/Authentication/ResourcesLocalClaimsTransformation.cs
- src/backend/api/Fusion.Resources.Api/Authentication/ResourcesLocalClaimsTransformation.cs
- src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
[AB#62509](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/62509)
Certain auth checks like is sibling resource owner would fail because the claims transformer would not be able to parse wildcard roles.
**Testing:**
**Checklist:**
> fix(resources): Handle wildcard* resource owner role
