equinor/fusion-app-resources

src/frontend/src/api/ApiClient.ts
src/frontend/src/api/ResourceCollection.ts
src/frontend/src/models/Person.ts
src/frontend/src/models/Personnel.ts
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/AddPersonnelSideSheet/AddPersonnelFormTextInput.tsx
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/AddPersonnelSideSheet/index.tsx

In Api client:
updatePersonnelAsync is now put and takes in person paramter.
New createPersonnelAsync created to handle post request.
resurceCollections updated to reflect this.
Models:
added created to Person model. Need this to differentiate between a locally created user and one from the api.
created and updated fields also added to Personnel.
PersonnelSide sheet and saving routine: 
When saving personnel it now checks if user is created to select correct endpoint.
When editing users email field is disabled for already created users.
Added placeholder to input fields, just so it still show data even if its disabled.

Fixed saving and creating users. disabled email edit for exisiting users

---

src/frontend/src/models/Personnel.ts
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelColumns.tsx
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/components/AzureAdStatus.tsx
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/getFilterSections.ts
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/index.tsx

Added filter pane to manage personnel. 
Has search option and filter for Ad status. 
Pulled out AzureAdStatus into its own component. 
So that the icons could be used in other places if needed. 
Wanted to use this in the filter pane, but that didnt work. 
Did extendt it though with some other functions. 
So you can pull out a "formatted" name for each status. 
And also color assosited with their icon.

Manage personnel Filter pane

---

src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/index.tsx
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/index.tsx
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/getFilterSections.ts

Notice this when setting up filters for mange personnel. 
Think this is unintended behaviour for the filters. 
Using the filtereddata to create a filterSections gives you filter selection based on the filtered data. 
Meaning you will not be able to select multiple statuses at once, because the rest disappear as soon as you select one. 
This changes makes it possible to select multiple status filters at the same time. 
It should still "remove" other filters thats empty in other filters.

update filterSection to use original nonefiltered datasource

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiBasePosition.cs
src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiContractPersonnel.cs
src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiExternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Api/Controllers/Personnel/PersonnelController.cs
src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
src/backend/api/Fusion.Resources.Database/Fusion.Resources.Database.csproj
src/backend/api/Fusion.Resources.Domain/Commands/Personnel/DeleteContractPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Commands/Personnel/UpdateContractPersonnel.cs
src/backend/api/Fusion.Resources.Domain/DbQueries/ContractPersonnelQueries.cs
src/backend/api/Fusion.Resources.Domain/Extensions/ODataParamsExtensions.cs
src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
src/backend/api/Fusion.Resources.Domain/Models/QueryBasePosition.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryContractPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryExternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryOrgPositionInstance.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryPersonnelRequestReference.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetContractPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetContractPersonnelItem.cs

Added support for fetching additional information on personnel.
**Positions**
Fetched using the resolved full profile. Only contract positions are included.
In list these can be included by ?$expand=positions.
**Requests**
Includes all requests the personnel item is included in. These can be different contracts/projects.
In list these can be included by ?$expand=requests.
Added endpoint for fetching a single personnel item. This can be referenced by using the mail/azure id or the personnel id. This is the id of the external personnel person item, not the personnel in contract relation id.

Api - Personnel details

---

src/frontend/src/pages/ProjectPage/components/EditContractWizard/index.tsx

added onChange handle when moving between pages in the stepper directly. else previous button didnt get mapped correctly
https://dev.azure.com/statoil-proview/Fusion/_backlogs/backlog/Fusion%20Team/Epics/?showParents=true&workitem=10659

Bug 10659 - Contract - Previous does not work when edit contract

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditableTable/index.tsx
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ContractDetailsPage/index.tsx

Bug 10758 :
Adjustment for Contract overview. 
Switched place off equinor company rep with equinor contract responisble.
Making the external and equinor version of these align. 
Bug 10761: 
edit/create request, if you remove thje workload the page crashes. 
This bug was created when fixing the same problem with Task owner. 
Sending inn empty string crashes task owener. 
But sending in null crashes workload. 
Fixes this by checking what null value to use. 
empty string for string values and null for other. 
Root of the problem is the TextInput "inputTextContentClasses". 
The value.length check here causing a crash when you send inn null.

Adjustment to contract Overview and fix create/edit position input

---

src/frontend/src/components/RequestProgressSidesheet/index.tsx
src/frontend/src/components/RequestProgressSidesheet/styles.less

Accordion takes up 100% of the height of its parent regardless of its own size. 
causing it to create a scroll even when empty, if there was failed/invalid attempts. 
Added a div around the accordian, so that is now scales more in height according to its own size.

10719 Actual MPP - Change request - Scroll on fly out

---

src/frontend/src/pages/ProjectPage/pages/ContractPage/components/EditablePositionDetails/index.tsx

When user didnt have azureId, PersonPhoto uses some default data on the picture hover.
Added personnel data to the person prop, that will be used when there is no azureID supplied.

added person info to use when user does not have azureId

---

src/backend/api/Fusion.Resources.Api/Controllers/Contracts/ContractsController.cs

Will give this response when project master not found now
```
{
"type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
"title": "Invalid Operation",
"status": 400,
"detail": "Unable to find project master for 'Query test project (01302859-f803-42a8-b6fa-4973bce5bc6b)'",
"error": {
"code": "ProjectMasterNotFoundError",
"message": "Unable to find project master for 'Query test project (01302859-f803-42a8-b6fa-4973bce5bc6b)'"
}
}
```

Changed status code to 400 from 404 on missing project master

---

src/frontend/src/pages/ProjectPage/pages/ContractPage/components/PositionDetailsSideSheet/hooks/useCurrentPosition.ts
src/frontend/src/pages/ProjectPage/pages/ContractPage/components/RequestDetailsSideSheet/hooks/useCurrentRequest.ts

Selected position/request initial state was null. A useEffect that removes the search string triggeres every time the state is null:
Set initial state to undefined and the useEffect will not trigger

Request and position side sheet - Closes on reload even tough id is specified in the url search string

---

src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/columns.tsx

when workload was zero, workload was shown as undefined. Checking if its a number instead

Actual Mpp - 0 workload shows as undefined%

---

src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/index.tsx

In managed personnel, it happens that "getPersonnelWithPositionsAsync" finnished before "getPersonnelAsync". 
And you end up with a dataset without positions. 
The fix I have added here works fine, but im unsure if its good for the long term.
With bigger datasets the final update/render might be delayed by alot. 
If you got any ideas on how this could be done better. 
Or a solution to explore im all ears. 
I have tried with a "flag" for getPersonnelWithPositionsAsync. 
So that if personnelwithPosition has sendt its dispatch. 
getPersonnelAsync will not return its result. 
That means that the fetchPersonnelAsync callback needs to listen to this flag. 
which leads to the function begin update and useReducerCollection will rerun the fetching.

Preventing Personnel with position begin overwritten by personnel without positions

---

src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/PersonnelInfoSideSheet/index.tsx

When you opened Managed personnel. 
There was a "Each child in a list should have a unique "key" prop" in the console.
Added keys to the header buttons array on the Personnelinfosidesheet.
Fixing the problem, and removing the error.

fixed error in console regarding missing list child keys

---

src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/index.tsx
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActualMppPage/index.tsx
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/CompletedRequestsPage/index.tsx
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ManagePersonnelPage/index.tsx
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ProvisioningRequestsPage/index.tsx

Replace entire collection of items instead of merge when fetching the entire collection from the backend

Use set instead of merge when fetching entire sets

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/pages/ProjectPage/pages/ContractPage/pages/ActiveRequestsPage/index.tsx

In active requests is where you're supposed to approve or reject the request. but now these buttons are way too hidden as is.
So what we need to do is: Make these buttons available at all times, these buttons should be inactive as long as no rows have been choosen. Once a row is chosen, then buttons should be set to active.

Bug 11638: Active requests - Make approval buttons available

---

src/backend/api/Fusion.Resources.Api/Controllers/ApiModels/ApiPerson.cs
src/backend/api/Fusion.Resources.Api/Controllers/Contracts/ContractsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/ContractPersonnelRequestRequest.cs

When nullable reference types are enabled, asp.net core validates non-nullable references on input models. The TaskOwner property on the position object was not marked as nullable, hence the default validator rejected the request.
Fixes AB#11362
**Testing:**
Simple fix, should not need testing.
**Checklist:**

Api - Fixed non-nullable taskowner on create request

---

src/backend/function/Fusion.Resources.Functions/Functions/Notification.cs

Damn, forgot the old runOnStartup.
**Testing:**
**Checklist:**

Resources - Notifications - RunOnStartup = false

---

src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs

Expanding orgPosition used the wrong property, and didn't expand.
Switched to id
**Testing:**
Updated tests to check if expansion work
**Checklist:**

Resources - Internal Requests - GetRequests doesn't expand orgPosition data when expected

---

src/backend/api/Fusion.Resources.Api/Startup.cs
src/backend/api/Fusion.Resources.Api/Swagger/AddApiVersionParameter.cs
src/backend/api/Fusion.Resources.Api/Swagger/FusionSwaggerConfig.cs
src/backend/api/Fusion.Resources.Api/Swagger/ODataQueryParamSwaggerFilter.cs
src/backend/api/Fusion.Resources.Api/Swagger/OptionalRouteParamFilter.cs
src/backend/api/Fusion.Resources.Api/Swagger/StartupExtensions.cs
src/backend/api/Fusion.Resources.Api/Swagger/SwaggerApiConfig.cs
src/backend/api/Fusion.Resources.Api/Swagger/SwaggerSetup.cs
src/backend/api/Fusion.Resources.Api/Swagger/ToStringTypeConverter.cs

Added api versioning support with default 1.0. This should let all existing endpoints work as execpted without having to provide a `?api-version=` param.
As uasability of swagger degrades when version is added, as the query param is not defined anywhere, we must add support for this by manipulating the output through swagger filters.
This filter adds a api-version query param to all endpoints and sets default value for a specific document. This means different versions must be added to different documents.
By making pages for different versions the usability of swagger ui improves, however using swagger to generate clients etc could see a 'hit'.
Also added swagger filters to make the complex models used in odata filtering usable, like removing the properties and …

Api versioning and swagger improvements

---

src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourcesApiWebAppFactory.cs

Fixed issue that caused running multiple integration test classes concurrently to fail.
The issue is rooted in the integration lib, where static variables is used to determine if a service config has been executed or not, to avoid adding duplicate services/event handlers. 
This works in a normal scenario where there is only running one service in the app domain, however when running integration tests, there are multiple web services starting up, running the same Startup class, but on different objects. 
The static variable is however only set once, therefor dependencies are not added in all test runs, causing service resolver error.
**Testing:**
Verified by running all integration tests
**Checklist:**

Api - Fixed concurrent integration test run issues

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs

Revisited routes. Mismatching occured.
Base is now: /resources/requests/internal
**Testing:**
changed routes in tests
**Checklist:**

Resources - Change route for internal requests

---

src/backend/api/Fusion.Resources.Domain/Commands/Roles/RecertifyContractReadRoleAssignment.cs

Internally in backend services code was using mediator.Publish instead of mediator.Send for a command.
Publish is used for Notifications
Send is used for Requests
CreateContractReadRoleAssignment is a Request, and since it was "Published" the handler expected was missing.
Using Send should utilize the request handler.
**Testing:**
**Checklist:**

Resources - Not able to re-certify outdated delegate

---

src/backend/api/Fusion.Resources.Domain/Services/PeopleCompanyResolver.cs

Existing resolver caches data for 12 hours. 
If a new company is added we may have to wait 12 hours until it is available.
Reduce cache time from 12 hours to 5 minutes
**Testing:**
**Checklist:**

Resources - PeopleCompanyResolver cache duration

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs

Added forced filter, which removed completed requests from the unassigned list. These might be unassigned but is not really relevant to list here.
**Testing:**
Can verify in api, as there should be some completed unallocated requests
**Checklist:**

Removed completed requests from the unassigned request list

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiInternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryInternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryPersonnelPosition.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryProject.cs
src/backend/api/Fusion.Resources.Domain/Utils/PeopleSearchUtils.cs

As the search index now has the manager property we can query on this property to get the personnel reporting to a department. This will give us a better view as the child department managers have their own department on the profile.
Added display of the new allocation state properties, which should indicate to the resource owner that the "task" has been updated after their person was allocated.
**Testing:**
Should verify in the resource owner app that the department is correct
**Checklist:**

Updated department personnel query and allocation metadata

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/DepartmentRequestsController.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentUnassignedRequests.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/UnassignedRequests/DepartmentUnassignedTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/FusionTestProjectBuilder.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Helpers/ApiPositionV2Extensions.cs

New endpoint at `/departments/{departmentPath}/resources/requests/unassigned` that will locate all unassigned requests that should be relevant for the department to claim.
The requests will be filtered using the department info located on the base position for the position the request is created on. 
Requests are included if the baeposition department is contained in the full department path or if the department is contained in the department path of the base position.
**Testing:**
TBD
**Checklist:**

Endpoint to get relevant unassigned requests for a department

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
src/backend/api/Fusion.Resources.Domain/Commands/Personnel/ResetAllocationState.cs
src/backend/api/Fusion.Resources.Domain/Identifiers/PersonId.cs
src/backend/api/Fusion.Resources.Domain/Identifiers/PersonnelId.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryPersonAbsence.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetPersonnelAllocation.cs
src/backend/api/Fusion.Resources.Domain/Utils/PeopleSearchUtils.cs

Added endpoint to reset allocation state on a persons allocation. This should be used by the resource owner to "accept" changes done by the task owner.
The operation will fetch the allocations for the user by using the profile search. From here the project and position id is resolved. Only the person id and instance id must be provided by the client.
**Testing:**
Should be verified by changing an position so the allocation state is updated in the search index. As this is mainly integration logic automated tests as skipped.
*Verified by updating allocation for person in org chart, then resetting using the endpoint. State set to null while allocation updated remains same date.*
**Checklist:**

Reset allocation state endpoint

---

src/backend/api/Fusion.Resources.Domain/Queries/GetDepartments.cs

Fix issue where expandin resource owners without resource owner search would only return CEO

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/DepartmentRequestsController.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentUnassignedRequests.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/UnassignedRequests/DepartmentUnassignedTests.cs

Add `$count` parameter to unassigned requests for department endpoint
**Testing:**
**Checklist:**

Add counting to relevant requests endpoint

---

src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/InitializedHandler.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/JointVentureRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs

When initializing workflow previously the state returned was 'created'.
Should return state id based on current workflow step
**Testing:**
Changed tests to reflect new state.
Can be verified when initializing workflow using client, checking state returned.
**Checklist:**

Internal Requests - Incorrect default state when initializing workflow

---

src/backend/api/Fusion.Resources.Api/Controllers/Person/ApiModels/ApiPersonNote.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/ApiModels/ApiResourceOwnerProfile.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/Requests/PersonNotesRequest.cs
src/backend/api/Fusion.Resources.Api/FusionEvents/ProfileSyncHandler.cs
src/backend/api/Fusion.Resources.Api/Startup.cs
src/backend/api/Fusion.Resources.Database/Entities/DbPersonAbsence.cs
src/backend/api/Fusion.Resources.Database/Entities/DbPersonNote.cs
src/backend/api/Fusion.Resources.Database/Migrations/20210417150335_Added person note.Designer.cs
src/backend/api/Fusion.Resources.Database/Migrations/20210417150335_Added person note.cs
src/backend/api/Fusion.Resources.Database/ResourcesDbContext.cs
src/backend/api/Fusion.Resources.Domain/Behaviours/RequestValidationBehavior.cs
src/backend/api/Fusion.Resources.Domain/Commands/Personnel/CreateContractPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Commands/Personnel/CreateOrUpdatePersonNote.cs
src/backend/api/Fusion.Resources.Domain/Commands/Personnel/DeletePersonNote.cs
src/backend/api/Fusion.Resources.Domain/Identifiers/PersonId.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryPersonNote.cs
src/backend/api/Fusion.Resources.Domain/NotificationHandlers/ClearPersonNotesHandler.cs
src/backend/api/Fusion.Resources.Domain/NotificationHandlers/ProfileUpdatedHandler.cs
src/backend/api/Fusion.Resources.Domain/Notifications/ProfileRemovedFromCompany.cs
src/backend/api/Fusion.Resources.Domain/Notifications/ProfileUpdated.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetPersonNotes.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonAbsenceTests.cs

Added endpoints to support adding notes to a resources. Instead of just one note the solution is based on a collection of notes, which can be labeled and support for marking specific items as shared. 
The idea is that some notes could be of a private nature, while others could be shared with other resource owners in the area (ex. what the person wants to work with etc). The public info could then be used in a search engine when locating candidates.
Endpoints are:
- GET|POST `/persons/{uniqueId|mail}/resources/notes`
- PUT|DELETE `/persons/{uniqueId|mail}/resources/notes/{noteId}`
Supported api version: `1.0-preview`
**Testing:**
Should be verified by frontend, to ensure initial usage is covered.
**Checklist:**

Person notes

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiInternalPersonnelPerson.cs

When applies to and applies from is the same date, the frontend cannot determine wether the end date is actually set. To prevent this, we can just send back the null value as is
**Testing:**
**Checklist:**

Avoid replacing absence to date with from date when null

---

src/backend/api/Fusion.Resources.Api/Authorization/Extensions/AuthorizationConfigurationExtensions.cs
src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
src/backend/api/Fusion.Resources.Api/Authorization/Handlers/OrgPositionAccessHandler.cs
src/backend/api/Fusion.Resources.Api/Authorization/Requirements/OrgPositionAccessRequirement.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourcesApiWebAppFactory.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/ProjectRequestAccessTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Api/Startup.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/OrgRequestInterceptor.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/OrgRequestMocker.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/OrgTestData.cs

Added authorization rules for the task owners on internal requests.
Based access on project membership and if user has read/write permission on the relevant position. This is done by executing an option call to the org api for the relevant position.
The option response is cached in 5 minutes to cover a short session.
**Testing:**
Will create integration tests.
**Checklist:**

Task owner authorization on requests

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiResourceAllocationRequest.cs
src/backend/api/Fusion.Resources.Application/LineOrg/LineOrgResolver.cs
src/backend/api/Fusion.Resources.Domain/Extensions/ODataParamsExtensions.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryResourceAllocationRequest.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetContractPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetContractPersonnelRequest.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetContractPersonnelRequests.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetDepartments.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequestItem.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/MockHttpClientBuilder.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourceApiFixture.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs

Add the possibility to expand details about the assigned department on requests. This will I.E. allow seeing the resource owner of the assigned department.
**Testing:**
**Checklist:**

Include assigned resource owner on requests

---

src/backend/api/Fusion.Resources.Domain/Extensions/IOrgApiClientExtensions.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequestItem.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Api/Controllers/PositionsController.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Fusion.Testing.Mocks.OrgService.csproj
src/backend/tests/Fusion.Testing.Mocks.OrgService/OrgServiceMock.cs

In some cases the task owner is incorrectly returned from resources. This might be based on manually calulating the relevant date. There is an endpoint that is specifically made to get the relevant taskowner for an exact instance, using either start/end or todays date.
Change expand task owner functionality in specific request query, to use the instance based endpoint.
**Testing:**
Should be verified by testing on future position
**Checklist:**

Updated to instance based task owner endpoint

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetDepartmentUnassignedRequests.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/UnassignedRequests/DepartmentUnassignedTests.cs

- Remove obsolete code for draft requests
- Update relevant departments endpoint to exclude drafts by using `ForRequestOwners` on request object.
**Testing:**
**Checklist:**

do not count draft requests as unassigned

---

src/backend/api/Fusion.Resources.Api/Controllers/ApiErrors.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/ResourceControllerBase.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/ResourceOwnerRequestTests.cs
src/backend/tests/Fusion.Testing.Core/Assertion/TestClientHttpResponseAssertions.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/FusionTestProjectBuilder.cs
src/backend/tests/Fusion.Testing.Mocks.ProfileService/PeopleServiceMock.cs

As some projects in pilot will be synced TO pims, while the rest is synced FROM pims, we must disable the possibility for resource owners to create change requests on allocations that will be overwritten from pims nightly.
The projects with pims write sync enabled should be safe to create change requests on.
We can do this by checking the property on the project. This is however a temporary solution in the pilot phase.
A check has been placed on `/projects/:orgProject/positions/:orgPositionId/instances/:orgInstanceId/resources/requests?requestType=resourceOwnerChange`. This will return `POST` in the `Allowed` header if request type can be created. For now only the `resourceOwnerChange` type is supported. If the request type is not supported, a bad request with …

Disable change requests for personnel in projects not in pilot

---

src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetDepartments.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsController.cs

Fall back to line org when fetching departments that do not exist in our database.
**Testing:**
**Checklist:**

fix department requests when not tracked in db

---

src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestsNotificationHandler.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequestItem.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiInternalRequestModel.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiTaskOwner.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationNotificationTests.cs

Existing code tries to notify positionId and not the person that is a task owner.
Fetching proper person(s) id(s) and adjusted recipient list
**Testing:**
Tested manually, updated integration tests
**Checklist:**

Resource Allocation - Notification - Task Owner fix

---

src/backend/api/Fusion.Resources.Api/Authorization/Extensions/AuthorizationConfigurationExtensions.cs
src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
src/backend/api/Fusion.Resources.Api/Authorization/Handlers/RequestCreatorHandler.cs
src/backend/api/Fusion.Resources.Api/Authorization/Requirements/RequestCreatorRequirement.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/PatchInternalRequestRequest.cs
src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourceApiFixture.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourcesApiWebAppFactory.cs
src/backend/tests/Fusion.Resources.Api.Tests/FusionMocks/AlwaysEmptyCache.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/ResourceOwnerRequestTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/OrgTestData.cs

- Add new auth requirement for request creator
- Implement security matrix for request creator
[Security Matrix](https://teams.microsoft.com/l/file/447EDF2B-9A6F-4163-A77E-E896A98E0617?tenantId=3aa4a235-b6e2-48d5-9195-7fcf05b459b0&fileType=xlsx&objectUrl=https%3A%2F%2Fstatoilsrm.sharepoint.com%2Fsites%2FProView190%2FShared%20Documents%2FFeatures%20-%20Resources%2FResource%20allocation%2FFusion-Resource-Allocation-API.xlsx&baseUrl=https%3A%2F%2Fstatoilsrm.sharepoint.com%2Fsites%2FProView190&serviceName=teams&threadId=19:1382bf30a0614a6b86a0a15c55a9833b@thread.skype&groupId=33a6ebec-c93b-47ae-94b9-fbc6fa6c4a4b)
**Testing:**
**Checklist:**

Add access control logic for request creators

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Logic/DeleteNotesHandler.cs
src/backend/api/Fusion.Resources.Logic/Events/RequestProvisioned.cs
src/backend/api/Fusion.Resources.Logic/Events/RequestProvisioningFailed.cs
src/backend/api/Fusion.Resources.Logic/Fusion.Resources.Logic.csproj
src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/ProvisionAllocationRequest.cs
src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Provision.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestComments.cs
src/backend/tests/Fusion.Resources.Logic.Tests/Provisioning/AllocationTests.cs

- Hide `GET` from options when request is completed to make it easier for frontend
- Delete comments when provisioning request.
**Testing:**
**Checklist:**

Hide resource owner notes when request is completed

---

src/backend/api/Fusion.Resources.Api/Notifications/InternalRequestsNotificationHandler.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationNotificationTests.cs

Should not send notitification to request initiator/user if user is creator/taskowner/resource owner of request
**Testing:**
Changed integration tests
**Checklist:**

Internal Requests - Notifications - Do not send notification to initiator

---

src/backend/api/Fusion.Resources.Api/Controllers/ResourceControllerBase.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/ResourceOwnerRequestTests.cs

Added support for additional flag on the project to enable resource owner change requests. 
This is needed as checking the pims write flag exclude too many projects in test environments.
**Testing:**
n/a
**Checklist:**

Added option to enable resource owner request on specific projects

---

src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs

Query filter field mapping was not updated after state changed from string column in db to complext object. Changed mapping to point to the the actual string value on the complex object.
Also added mapping for "hidden" field `state.isComplete`.
**Testing:**
**Checklist:**

Fixed filter field mapping for request state

---

src/backend/api/Fusion.Resources.Api/Authorization/Extensions/AuthorizationConfigurationExtensions.cs
src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
src/backend/api/Fusion.Resources.Api/Authorization/Handlers/OrgProjectAccessHandler.cs
src/backend/api/Fusion.Resources.Api/Authorization/Requirements/OrgProjectAccessRequirement.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/ProjectRequestAccessTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/FusionTestProjectBuilder.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Resolvers/OrgResolverMock.cs

Added support for granting read access to request for a project when the user has read access in the org chart.
**Testing:**
Added test to verify access is granted when project option endpoint is queried.
**Checklist:**

Read access to requests for project update

---

src/backend/api/Fusion.Resources.Domain/Queries/GetDepartments.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsController.cs

Correctly check if search is limited to specific departments before filtering results from line org.
**Testing:**
**Checklist:**

Department search: return items from line org when department not tracked in db

---

src/backend/api/Fusion.Resources.Api/Controllers/Person/ApiModels/ApiPersonAbsence.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/ApiModels/ApiTaskDetails.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonAbsenceController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/Requests/CreatePersonAbsenceRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/Requests/UpdatePersonAbsenceRequest.cs
src/backend/api/Fusion.Resources.Database/Entities/DbPersonAbsence.cs
src/backend/api/Fusion.Resources.Database/Migrations/20210526142847_add_task_details_to_absence.Designer.cs
src/backend/api/Fusion.Resources.Database/Migrations/20210526142847_add_task_details_to_absence.cs
src/backend/api/Fusion.Resources.Domain/Commands/EmploymentStatus/CreatePersonAbsence.cs
src/backend/api/Fusion.Resources.Domain/Commands/EmploymentStatus/UpdatePersonAbsence.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryPersonAbsence.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetPersonAbsence.cs
src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonAbsenceTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Api/Controllers/PositionsController.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/FusionTestProjectBuilder.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Helpers/TestPositionBuilder.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/OrgServiceMock.cs

Add `TaskDetails` to `PersonAbsence` to describe work on other tasks.
Hide this information for other resource owners except in parent and sibling departments.
**Testing:**
**Checklist:**

Add task details to other tasks

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/PatchInternalRequestRequest.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs

Allow unsetting proposed person when request is not sent for task owner approval.
**Testing:**
**Checklist:**

Allow removing proposed person when request is not proposed yet

---

pipelines/api-pipeline.yml

After update to latest kubernetes version the ingres version had to be updated to latest non-beta version. This has only been done on the test cluster, not the production cluster. 
This makes the deploy to production cluster step fail. As this is only a pilot and not used by production, this should be disabled untill the production cluster has been recreated.
**Testing:**
**Checklist:**

Pipeline - Disabled production k8s deploy

---

src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-test-env.yml
src/frontend/k8s/deployment.template.yml

Fix deprecated annotation for cert renewal.
**Testing:**
**Checklist:**

fix k8s ingress cert renewal

---

src/backend/api/Fusion.Resources.Api/Controllers/Person/Requests/CreatePersonAbsenceRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/Requests/UpdatePersonAbsenceRequest.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonAbsenceTests.cs

Fix validation so that either base position id or role name is required for task details.
[AB#21184](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/21184)
**Testing:**
**Checklist:**

Fix validation of rolename/baseposition in task details

---

src/backend/api/Fusion.Resources.Api/Controllers/ResponsibilityMatrix/Requests/UpdateResponsibilityMatrixRequest.cs
src/backend/api/Fusion.Resources.Domain/Commands/ResponsibilityMatrix/CreateResponsibilityMatrix.cs
src/backend/api/Fusion.Resources.Domain/Commands/ResponsibilityMatrix/UpdateResponsibilityMatrix.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/ResponsibilityMatrixTests.cs

Require a unit set for responsibility matrix so that requests are actually routed somewhere.
**Testing:**
**Checklist:**

Require unit for responsibility matrix

---

src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/AddDelegatedResourceOwnerRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/AddDepartmentRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/ApiDepartment.cs
src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/ApiRelatedDepartments.cs
src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/ApiRelevantDepartments.cs
src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/UpdateDepartmentRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiResourceAllocationRequest.cs
src/backend/api/Fusion.Resources.Domain/Commands/Departments/GetRelatedDepartments.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryRelatedDepartments.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceOwnerProfile.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsController.cs

Ignore CEO's department when getting relevant department. [AB#21348](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/21348)
**Testing:**
**Checklist:**

Do not return CEO's department as relevant when baseposition department is empty string

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentPersonnel.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiPersonnelPerson.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
src/backend/tests/Fusion.Testing.Mocks.ProfileService/Api/PersonsController.cs
src/backend/tests/Fusion.Testing.Mocks.ProfileService/Fusion.Testing.Mocks.ProfileService.csproj
src/backend/tests/Fusion.Testing.Mocks.ProfileService/PeopleServiceMock.cs

Avoid loading positions that are outside the timeline range. The current functionality wastes a lot of bandwith.
**Testing:**
**Checklist:**

Hide past allocations in timeline

---

src/backend/api/Fusion.Resources.Domain/Services/RequestRouter.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsController.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
src/backend/tests/Fusion.Resources.Logic.Tests/RequestAssignment.cs

Remove code that gave relevant positions a higher score leading to incorrect results now that only relevant positions should be considered.
**Testing:**
**Checklist:**

Fix relevant position scored too high in routing

---

src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonController.cs
src/backend/api/Fusion.Resources.Domain/Errors/NotAuthorizedException.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceOwnerProfile.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonControllerTests.cs

Return empty resource owner profile when user has no department, i.e. user is an affiliate account. 
Return 404 when user does not exist at all.
[AB#22337](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/22337)
**Testing:**
**Checklist:**

Avoid internal server error when missing department

---

pipelines/environment-pipeline.yml
src/backend/infrastructure/deploy-resources.ps1

The PR env pipeline will generate a secret in the key vault, which is loaded on api startup. This secret will override the env variable used to direct the pr slot to the correct PR database. 
To solve this the secret should be deleted in key vault after template has been executed. This is a simpler solution than designing the templates to conditionally add the secret. 
Running pods should not be affected by the key vault, unless they are doing a restart at the exact same seconds..
**Testing:**
Verify by running pipeline on branch and PR stage.
**Checklist:**

Infra - Fix incorrect db connection string in pr environments

---

src/backend/api/Fusion.Resources.Api/Startup.cs

Enabled displaying the sql command texts in the AI dependency traces.
This was disabled by default some time ago. This change has apparently not been done in this api.
**Testing:**
Verified by debugging and checking that AI traces actually contains sql commands.
**Checklist:**
Fixes [AB#23320](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/23320)

AI - Added sql command text to dependency traces

---

src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
src/backend/api/Fusion.Resources.Api/Controllers/Contracts/ContractsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Mpp/MppController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Personnel/PersonnelController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Projects/ProjectsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/RequestsController.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourceApiFixture.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/ExternalPersonnel/ExternalPersonnelTests.cs

Added new full control role for external endpoints. This will allow grant admin permissions to external parts of the api only.
Role name `Fusion.Resources.External.FullControl`. The role should be bound to a group as a claimable role.
Fixes [AB#22411](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/22411)
**Testing:**
Updated all integration tests to use the new role instead of the global full control role. However this does not cover every part.
Will be difficult to test a pr branch, so should roll out and verify in CI. 
The new role should not interfear with existing functionality.
**Checklist:**

Add full control role for external personnel endpoints

---

src/backend/api/Fusion.Resources.Domain/Identifiers/PersonId.cs
src/backend/api/Fusion.Resources.Logic/Requests/Commands/ContractorPersonnelRequest/Provision.cs

When provisioning allocations to the org service the request only used mail to identify person. 
When the account has no mail, this fails.
Fixed by using azure id primarily, and only use mail as a fallback.
**Testing:**
Can be verified by creating request on a person with no mail. Provisioning step should be successfull.
**Checklist:**
Skipping automatic test to get functionality out quickly. Simple fix with low risk.

External - Fixed provisining issue where persons have no mail

---

src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
src/backend/api/Fusion.Resources.Api/Controllers/ResponsibilityMatrix/ResponsibilityMatrixController.cs
src/backend/api/Fusion.Resources.Domain/Utils/DepartmentPath.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/ResponsibilityMatrixTests.cs

Updated authorization rules for the responebility matrix, to allow resource owners access to items relevant for their department.
This allows them to create items targeting their own department, as well as their sibling/parent to increase the usability. 
The sibling/parent can be removed if found to broad. However I do belive they should be able to cooperate on this across a typical sector.
**Testing:**
Should deploy app to use the pr api
**Checklist:**
Fixes [AB#24008](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/24008)

Allow resource owners access to responsebility matrix for their department

---

src/backend/api/Fusion.Resources.Domain/Extensions/FusionPersonProfileExtensions.cs
src/backend/api/Fusion.Resources.Domain/Services/ProfileServices.cs
src/backend/function/Fusion.Resources.Functions/Functions/ProfileSync.cs

Azure function which synchronizes profiles does not properly consider removed profiles.
* When ensuring profiles, we currently only update profiles for successfully ensured profiles. Should include all.
* Expired profiles not ensured, should be considered and processed when updating/synchronizing external personnel.
* An external person without invitationstatus should not be considered available, but without an account.
Work item:
[AB#23690](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/23690)
~~Depends on:[AB#24244](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/24244)~~ Already COMPLETED & Deployed
**Testing:**
**Checklist:**

Profile Sync function -  External personnel improvements

---

src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Initialize.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationNotificationTests.cs

When a position is marked as enterprise position, and enterprise personnel is added and auto approved, there should not be sent a notification to task owner due to auto approval.
Starting the workflow should not dispatch AssignedDepartment notification for enterprise requests. 
[AB#24980](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/24980)
**Testing:**
**Checklist:**

API - Don't send notification to task owner for enterprise positions

---

src/backend/api/Fusion.Resources.Application/ServiceBus/IQueueSender.cs
src/backend/api/Fusion.Resources.Application/ServiceBus/ServiceBusService.cs
src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/QueueProvisioning.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourcesApiWebAppFactory.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/DirectRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs

* Implement delayed service bus message sender, and use this option when enqueueing provisioning request.
[AB#25126](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/25126)
**Testing:**
**Checklist:**

API - Add option to add scheduled enqueue time for service bus message

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiContractPersonnel.cs
src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiExternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Database/Entities/DbExternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Database/Migrations/20220114134754_ExternalPersonnel DELETED property added.Designer.cs
src/backend/api/Fusion.Resources.Database/Migrations/20220114134754_ExternalPersonnel DELETED property added.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryContractPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryExternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetContractPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetContractPersonnelRequests.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetExternalPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Services/ProfileServices.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiPersonnel.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/ExternalPersonnel/ExternalPersonnelTests.cs

* Added DELETED property to DBExternalPersonnel
* Added IsDeleted & DELETED to query models (QueryContractPersonnel/QueryExternalPersonnelPerson)
* Added IsDeleted & DELETED to api models/odata filters (ApiContractPersonnel/ApiExternalPersonnelPerson)
* Added DELETED to be updated during profile refresh (IsDeleted already being updated)
[AB#25133](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/25133)
**Testing:**
**Checklist:**

API - ExternalPersonnel handle/expose properties indicating users deleted in azure

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiInternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiRequestStatus.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryPersonnelPosition.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryRequestStatus.cs
src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Utils/PeopleSearchUtils.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiPersonnelPerson.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs

[AB#24965](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/24965)
- Add `ChangeRequestStatus` property on personnel position classes to enable frontend to display different statuses differently
**Testing:**
**Checklist:**

Add `ChangeRequestStatus` to Person Position Timeline

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/PersonnelController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Personnel/Requests/ReplaceContractPersonnelRequest.cs
src/backend/api/Fusion.Resources.Database/Entities/DbContractPersonnelReplacement.cs
src/backend/api/Fusion.Resources.Database/Entities/DbExternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Database/Migrations/20220127125233_ContractPersonnelReplacementAuditing.Designer.cs
src/backend/api/Fusion.Resources.Database/Migrations/20220127125233_ContractPersonnelReplacementAuditing.cs
src/backend/api/Fusion.Resources.Database/ResourcesDbContext.cs
src/backend/api/Fusion.Resources.Domain/Commands/Personnel/CreateContractPersonnelReplacementAudit.cs
src/backend/api/Fusion.Resources.Domain/Commands/Personnel/ReplaceContractPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Commands/Personnel/ReplaceProjectPositionInstancesAssignedPerson.cs
src/backend/api/Fusion.Resources.Domain/Extensions/IOrgApiClientExtensions.cs
src/backend/api/Fusion.Resources.Domain/Extensions/JsonNetExtensions.cs
src/backend/api/Fusion.Resources.Domain/Services/IProfileServices.cs
src/backend/api/Fusion.Resources.Domain/Services/ProfileServices.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiPersonnel.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/ContractPersonnelReplacementTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Api/Controllers/PositionsController.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/OrgServiceMock.cs
src/backend/tests/Fusion.Testing.Mocks.ProfileService/PeopleServiceMock.cs

The admins for a contract should have an option to "replace" the account with a new one.
[AB#25134](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/25134)
[DOCS link](https://docs.fusion-dev.net/pr-163/domain/services/resources/tech-specs/replace-expired-accounts/)
**Testing:**
To be able to test, we require new and old accounts.
I can see MARTIN.SANDEN@AIBEL.COM to exist in CI with expired and new account.
The old account is used in Oseberg Gas Capacity Upgrade (OGP) project on the Aibel OGP EPCI contract
and Query test project on the Test contract
**Checklist:**

API - ContractPersonnel - Replace person

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/RequestActionsController.cs
src/backend/api/Fusion.Resources.Logic/DeleteActionsHandler.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestActionTests.cs
src/backend/tests/Fusion.Resources.Logic.Tests/Provisioning/AllocationTests.cs

[AB#25080](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/25080)
Implement same functionality for follow-up actions as notes.
- Actions are cleared when request is completed.
- Adding new actions after completion is no longer permitted.
**Testing:**
**Checklist:**

Delete actions when request is provisioned

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiContractPersonnel.cs
src/backend/api/Fusion.Resources.Api/Controllers/Personnel/ApiModels/ApiExternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Database/Entities/DbExternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Database/Migrations/20220209100249_ExternalPersonnelIsDeletedNull.Designer.cs
src/backend/api/Fusion.Resources.Database/Migrations/20220209100249_ExternalPersonnelIsDeletedNull.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryContractPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryExternalPersonnelPerson.cs
src/backend/api/Fusion.Resources.Domain/Services/ProfileServices.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Rsponses/TestApiPersonnel.cs

* Existing solution doesn't handle IsDeleted flag properly.
* Should be TRUE only IF the account identified from PEOPLE service having AzureUniqueId and being expired
* Should be NULL by default
[AB#26116](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/26116)
**Testing:**
**Checklist:**

API - ExternalPersonnel - Nullable IsDeleted flag

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/CreateResourceAllocationRequest.cs
src/backend/api/Fusion.Resources.Domain/Utils/DepartmentPath.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/DirectRequestTests.cs

[AB#26101](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/26101)
It should not be possible to assign a direct request to a different department than the one the proposed person is in.
**Testing:**
**Checklist:**

Reject direct requests when assignedDeparment != proposedPerson.department

---

src/backend/api/Fusion.Resources.Domain/Diagnostics/FusionTelemetryEvents.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetContractPersonnel.cs

Current implementation throws exception during expand of positions while iterating non-existing persons fetching contract personnel.
* Ensure this problem is being tracked as Critical Event. (Should not happen, but did when we broke azureUniqueIds manually)
* Continue processing if unable to expand positions for "invalid" user accounts
[AB#26134](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/26134)
**Testing:**
**Checklist:**

API - GetContractPersonnel - Expand position crash

---

pipelines/templates/grant-database-app-access.yml
src/backend/api/Fusion.Resources.Api/Deployment/deploy-webapp.ps1
src/backend/infrastructure/grant-adapp-sql-access.ps1

Current pipeline is using Get-AzKeyVaultSecret
Assigning to variable and try to use .SecretValueText doesn't work anymore.
Could use -AsPlainText to get the value directly and assign to variable.
* File [grant-database-app-access.yml](https://github.com/equinor/fusion-app-resources/pull/471/files#diff-71de94f9506b85399113638e3b207a37ded9c6b8363684c6f3a78dde4d9b0298) seems to be left in code for historic reason. Decided to update anyway.
* File [deploy-webapp.ps1](https://github.com/equinor/fusion-app-resources/pull/471/files#diff-30d4d099f72f4e92e4c2a89823a2273362edcaf62138215920a7faa4a87445db) is used for deploy to PROD (currently using webapp and not cluster)
* File [grant-adapp-sql-access.ps1](https://github.com/equinor/fusion-app-resources/pull/471/files#diff-d …

INFRA - Get-AzKeyVaultSecret - breaking change in latest version

---

pipelines/secret-rotation-pipeline.yml
src/backend/infrastructure/generate-secret.ps1

Updated the pipeline to use latest version of powershell, which allows setting a display name for the secrets generated. This leads to improved visibility when inspecting expiring secrets etc.
Issues encountered due to bugs in the PS module at version 7.1.0, which is default on hosted agents. Resolved this by forcing 7.2.0 version which is normally pre-installed on the agents.

Key rotation pipeline update

---

src/backend/api/Fusion.Resources.Api/Controllers/Person/ApiModels/ApiPersonAllocationRequestStatus.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonController.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceOwner.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourceApiFixture.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonControllerTests.cs
src/backend/tests/Fusion.Testing.Mocks.ProfileService/PeopleServiceMock.cs

Added manager object to the endpoint listing allocation status for a person.
This allows to frontend to get all relevant info in one go.
Updated the query that use uncached request to lineorg to resolve manager, to use the profile instead, as the property is now included her.
**Testing:**
Added test to verify manager is populated.
**Checklist:**

Manager info on the person allocation status endpoint

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs

Current implementation does only allow the creator of a request to delete it only if the request is of type Allocation. An issue occurred where the creator of a change request wanted to delete it, but did not have authorization. The proposed change is to allow the creator of requests, regardless of request type, to have authorization to delete the created request.
[AB#27424](https://dev.azure.com/statoil-proview/Fusion/_workitems/edit/27424)
**Testing:**
**Checklist:**

API - Internal Requests - Update authorization rule on delete endpoint

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/ConversationsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/RequestActionsController.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequestItem.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs

AB#27683
Elin reported that request actions and notes should never be visible to task owners. This PR is a temporary fix to remove access to request notes for for anyone not a resource owner.
**Testing:**
**Checklist:**

Restrict access to request notes

---

src/backend/api/Fusion.Resources.Domain/Services/ProfileServices.cs

Initialize NoProfileCacheScope before resolving profile during refresh.
Should ensure that a fresh profile is resolved before matcing with external personnel entry
**Testing:**
**Checklist:**

ProfileSync - No cache scope

---

src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiActionCount.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiResourceAllocationRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/ConversationsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/RequestActionsController.cs
src/backend/api/Fusion.Resources.Domain/Commands/Conversations/GetRequestConversation.cs
src/backend/api/Fusion.Resources.Domain/Commands/Tasks/CountActionsForRequests.cs
src/backend/api/Fusion.Resources.Domain/Commands/Tasks/GetActionsForRequests.cs
src/backend/api/Fusion.Resources.Domain/Commands/Tasks/GetRequestAction.cs
src/backend/api/Fusion.Resources.Domain/Commands/Tasks/GetRequestActions.cs
src/backend/api/Fusion.Resources.Domain/Commands/Tasks/QueryTaskSource.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryResourceAllocationRequest.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequestItem.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/ResourceOwnerRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestActionTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestConversationTests.cs

Proper fix for AB#27683
- Split request endpoints into two areas: `/project/{projectId}` and `/departments/{departmentId}`
- This allows us to simplify access control for endpoints, because only task owners need access to the /project/ area, while only resource owners need access to the /departments area.
- It also makes it possible to query actions and conversations by recipient/responsible without checking user information in the domain handlers.
- Add actionCount to request list endpoint to enable showing unresolved action count in list view without expanding all action data.
**Testing:**
**Checklist:**

Open up request conversations/actions for task owners when they are the recipient

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Api/FusionEvents/Handlers/InternalRequests/UpdateOrgPositionInstanceHaveRequestHandler.cs
src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/UpdateOrgPositionInstanceHaveRequest.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Api/Controllers/PositionsController.cs

When creating or deleting request, logic should update hasRequest property on pro-org position instance.
true if request is created
false if request is deleted
Property does not exist if no request exists. Property may exist on older instances created based on PIMS as source.
(Previously requests where handled in PIMS)
AB#28770
**Testing:**
Should be able to verify using histograms in Pro-Org app.
Creating request, should tag instance. Should reflect in historgram's.
**Checklist:**

Pro-Org - Positions having allocation request missing in org-chart histogram

---

src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/UpdateOrgPositionInstanceHaveRequest.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/OrgServiceMock.cs

When trying to delete a request where linked org position instance was deleted, request failed.
Should be allowed to remove request, even if linked org position instance doesn't exist anymore.
(Currently about 175 instances with requests has been deleted)
AB#29287
**Testing:**
**Checklist:**

Unable to remove resource allocation request when pro-org position instance is already deleted

---

src/backend/api/Fusion.Resources.Domain/Queries/GetTBNPositions.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourceApiFixture.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourcesApiWebAppFactory.cs
src/backend/tests/Fusion.Resources.Api.Tests/GetTbnPositionTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Api/Controllers/PositionsController.cs

AB#29030
Ignore TBN positions that are above resource owner department in line org.
**Testing:**
**Checklist:**

Hide TBN positions when above department in line org

---

src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/UpdateOrgPositionInstanceHaveRequest.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/OrgServiceMock.cs

When trying to delete a request, where the ORG Project Position is already removed, you will receive an error.
Make sure we are able to delete an internal resource allocation request even if ORG position is deleted.
[AB#30371](https://dev.azure.com/statoil-proview/Fusion/_workitems/edit/30371)
**Testing:**
Tried to remove locally connecting a request to a non existing position guid
In CI you can verify this by trying to delete requests missing positions found [here](https://pro-s-portal-ci.azurewebsites.net/apps/org-admin/29ddab36-e7a9-418b-a9e4-8cfbc9591274/open-requests)
**Checklist:**

API - Exception when trying to remove request where position in ORG is already deleted

---

src/backend/api/Fusion.Resources.Logic/CloseSecondOpinionsHandler.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/SecondOpinionTests.cs

Prevent second opinions from being hidden after request completion.
AB#30775
**Testing:**
**Checklist:**

Avoid removing comments when request is completed

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/SecondOpinionController.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/SecondOpinionTests.cs

AB#30955
**Testing:**
**Checklist:**

Fix inconsistent Allow header in OPTIONS for completed rquests

---

src/backend/api/Fusion.Resources.Domain/NotificationHandlers/ProfileUpdatedHandler.cs

When backend receives a ProfileUpdated event, we ensure local profile is updated.
However we don't flush the fusion profile resolver cache.
Ensure updated user is removed from cache during ProfileUpdatedHandler
[AB#31121](https://dev.azure.com/statoil-proview/Fusion/_workitems/edit/32121)
**Testing:**
**Checklist:**

When a profile is updated, updated users may still remain in cache.

---

src/backend/Fusion.Resources.Authorization/Fusion.Resources.Authorization.csproj
src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
src/backend/api/Fusion.Resources.Application/Fusion.Resources.Application.csproj
src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
src/backend/function/Fusion.Resources.Functions/Fusion.Resources.Functions.csproj
src/backend/tests/Fusion.Testing.Authentication/Fusion.Testing.Authentication.csproj
src/backend/tests/Fusion.Testing.Core/Fusion.Testing.Core.csproj
src/backend/tests/Fusion.Testing.Mocks.ContextService/Fusion.Testing.Mocks.ContextService.csproj
src/backend/tests/Fusion.Testing.Mocks.OrgService/Fusion.Testing.Mocks.OrgService.csproj
src/backend/tests/Fusion.Testing.Mocks.ProfileService/Fusion.Testing.Mocks.ProfileService.csproj

When trying to initiate workflow when context-cache in integration library contains multiple cache items of same id, backend endpoint crashed.
Fixed by adding duplicate-check in integration library.
Solved here by upgrading nuget packages, referencing newer versions of fusion packages.
AB#32221
**Testing:**
**Checklist:**

Context issue when trying to initiate workflow

---

src/backend/api/Fusion.Resources.Api/Controllers/ApiModels/ApiPerson.cs
src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiProposedPerson.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/ApiModels/ApiResourceAllocationRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryProposedPerson.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryResourceAllocationRequest.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequestItem.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceAllocationRequests.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Responses/TestApiPerson.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Responses/TestApiProposedPerson.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsController.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonControllerTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/SearchDepartments.cs
src/backend/tests/Fusion.Testing.Core/Http/TestClientHttpResponse.cs

Updated department/{id} to default expand delegatedResourceOwners 
Updated apiProposedPerson and QueryProposedPerson
Expanding resoure onwer should now also expand delegatedResrouceOwners
**Testing:**
by verifying that the delegatedResourceOwners property has the desired data neccesary
**Checklist:**

Add delegated resource owners to ApiDepartment model

---

src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs

GetPositionDepartments needed to also return ExpandedDelegatedDepartments, the api suggested it already did, but the expanded method was not added to actualy return the data. 
[AB#33250](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33250)
**Testing:**
Have tested localy and it now returns expandedDelegatedResouceOwners
**Checklist:**

GetPositionDepartments needed to also return ExpandedDelegatedDepartments

---

src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentHandlerBase.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetDelegatedDepartmentResponsibles.cs
src/backend/tests/Fusion.Resources.Api.Tests/Fixture/ResourceApiFixture.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonControllerTests.cs

Updated ExpandDelegatedResoureOwner to use DateTo and DateFrom in query parameters to filter out expired or future positions.
There have also been created tests that check for the DateTo and From,  som code have been cheng in relation to that to help facilitate the test. wihtout breakting eksisting functionality
**Testing:**
Can be tested by running a get request against the endpoint /delegated-resource-owners, where there is a user that have a future or expired delegation.  one way is to delegate a user acces today with expiration today, and wait unitl tomorrow. 
**Checklist:**
[AB#35362](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/35362)

Querying delegated department responsibles doesnt consider valid dateframe

---

src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Queries/Departments/ResolveLineOrgUnit.cs
src/backend/api/Fusion.Resources.Domain/Utils/PeopleSearchUtils.cs

Problems have been identified with the query used to resolve employees in a department, when changing to a context based personnel app.
We cannot use the manager as reference as there are no guarantee that the manager in only manager for the specific department. A person can be manager for multiple departments at the same time, in cases where one has not yet been employeed. 
When there is no maanger, the responsibility falls to the next level up, in SAP, which is synced to AD. 
The v1 view is working with the current app where the manager will get all departments in the same view.. If we update the v1 endpoint, the current app will not work. We cannot publish the new app, as this would make it unusable for the users with multiple departments.
Solution is to …

feat(api): V2 endpoint for listing department personnel

---

src/backend/api/Fusion.Resources.Api/Deployment/webapp.template.json

When users receive notifications which lets them open relevant resources in the portal, the hostname is using the old value which is configured to redirect users. 
This creates issues when the browser has to run an signin session at the same time, due to oauth flow.
The portal url is resolved through integration lib. This should be updated to the latest version, but this requires more testing. 
Added quick fix, where resolved host can be overridden through web app config. Updated the web app template for prod to set fusion.equinor.com as hostname for portal.
**Testing:**
Cannot be tested except for in production environment.
**Checklist:**

fix(api): Users cannot open fusion portal from notifications

---

src/backend/api/Fusion.Resources.Api/Controllers/Admin.cs
src/backend/api/Fusion.Resources.Api/Controllers/Departments/InternalDepartmentsController.cs
src/backend/api/Fusion.Resources.Api/FusionEvents/LineOrgOrgUnitHandler.cs
src/backend/api/Fusion.Resources.Api/Startup.cs

The LineOrgOrgUnitChangedEvent was not added to the Startup.cs resulting it never listening for lineOrgUnit Changes events. 
also added a ability to cleare the cache if needed
**Testing:**
**Checklist:**

Added LineOrgUnitChangedEvent and possiblity to cleare cache if needed

---

src/backend/api/Fusion.Resources.Api/Controllers/Person/ApiModels/ApiPersonAbsence.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonAbsenceController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/Requests/CreatePersonAbsenceRequest.cs
src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
src/backend/api/Fusion.Resources.Api/Swagger/SwaggerSetup.cs
src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/DirectRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/EnterpriseRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/JointVentureRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/NormalRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/ProjectRequestAccessTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/ResourceOwnerRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationNotificationTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonAbsenceTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonControllerTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonNotesTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestActionTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestComments.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/RequestConversationTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/ResponsibilityMatrixTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/SearchDepartments.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/SecondOpinionTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/SharedRequestTests.cs
src/backend/tests/Fusion.Testing.Core/TestDbConnectionStrings.cs

Added new endpoint which only returns absence of type `OtherTask` and marked public. 
This seems to have changed purpose in the UI, but the backend still considers the private flag differently.
Updated the current endpoint that returns absence, to only return non private additional tasks when the user is just a normal employee
**Testing:**
TBD
**Checklist:**

feat: Endpoint for additional tasks

---

src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentPersonnel.cs

When a User is manager in more than one Departmetn at the same Level, then the search results returnes the personnel from all departments the manager is managing. 
To help mitigate this the code is chagned to also include "isResourceOwner eq true"
This should help remove the problem with the personnell showing in wrong departments. 
Ther are howere cases we need to think  about if is applicable. 
- Should DelegatedResposibility users also be included?
- Should whe check for the role Fusion.ResourseOwner and include them? do they appear as managers in eq One Equinor?
- this appears to be Identical code that are in **LineOrg Service** file  **ListOrgUnitEmployees.cs**
[AB#41694](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/ …

Updated the PeopleSearchIndex Query to support same manager on multiple Departments at same Level

---

src/backend/api/Fusion.Resources.Api/Controllers/Person/ApiModels/ApiPersonAbsence.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonAbsenceController.cs
src/backend/api/Fusion.Resources.Domain/Queries/Departments/GetDepartmentPersonnel.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetPersonAbsence.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonAbsenceTests.cs

Non-private open tasks are visible for all employees to view. However past other tasks should not be visible due to current GDPR limitations.
Refactored trimming logic to be done in the query instead of controller since it is used in multiple endpoints.
**Testing:**
Verified by tests
**Checklist:**

fix: Hide expired other task from open view

---

src/backend/api/Fusion.Resources.Domain/Identifiers/PersonId.cs
src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/DirectAllocationRequestStarted.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/DirectRequestTests.cs

After the removal of enterprise personnel type property was removed on the positions, it has not been possible to add joint venture/guest accounts to any org charts.
This is due to the direct request assumed that only ad accounts would be used, so the department should exist. 
Updated the validation of direct request initialization to not require the request be assigned to a department if a external account type is proposed.
**Testing:**
Verified by completing a request which failed in CI. 
Created automatic test verifying error and fix
**Checklist:**
Fixes: [AB#43169](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/43169)

feat: Support joint venture account in direct request

---

src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs

Added a role neede to be able to read from Fusion.Resources. Only added specifically to GetAllRequests endpoint (resources/requests/internal)
**Testing:**
Strip down user and try to access that specific endpoint without any roles claimed. And then try to add that specific role, and observe that it is allowed to use the endpoint. Applies to endpoint "resources/requests/internal"
[AB#43635](https://statoil-proview.visualstudio.com/Fusion%20Resource%20Allocation/_workitems/edit/43635)
**Checklist:**

feat: Add Fusion.Resources.Read role to GetAllRequests endpoint

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/SecondOpinionController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Utilities/UtilitiesController.cs

fix(api): Unhandled exceptions fix

---

src/backend/api/Fusion.Resources.Domain/Queries/GetPersonProfiles.cs

Was using the wrong variable when looping through all PersonIdentifiers from the request. Changed to the correct variable
**Testing:**
**Checklist:**

fix: Change variable name when getting PersonProfile from PersonAPI

---

src/backend/api/Fusion.Resources.Domain/Commands/Requests/InternalRequests/ResetWorkflow.cs

When resetting workflow as a step in rejecting a AllocationRequest I have removed functionality to set ProposedPerson to NULL. This is an attempt to make ProposedPerson available when the task owner is responding to a rejected request, which should be to create a new request. It is then easier to know who was the previous suggested resource before creating a new request
**Testing:**
Can be tested by creating a new request with a specific resource (as proposedPerson). Then the resource owner should reject the request. The rejected request should then still contain the proposedPerson suggested in the first step.
**Checklist:**

feat: Do not set ProposedPerson = NULL when ResetWorkflow

---

src/backend/function/Fusion.Resources.Functions/ServiceBus/QueueMessageProcessor.cs

[AB#44549](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/44549)
Because there have been some requests that have timed out when running its natural cause and there are not obvious exceptions we will try to increase the amount of time we delay the retry. We increase from 10 seconds * retryCount to 30 seconds * retryCount. This means that we will wait around 4 minutes before retrying the last time (fourth time).
NB! The initial code did prepare scheduledTime to be increased 10 seconds for each retry, but the value was never assigned to retryMessage. We will still increase the delay to be 30 seconds for each try.
**Testing:**
The function could be tested with natural processing of a request going through all the stages …

fix: Increased time of delay for each retry of queued message (Provision)

---

.github/workflows/test-api.yml
src/backend/.config/dotnet-tools.json
src/backend/Fusion.Resources.Authorization/Fusion.Resources.Authorization.csproj
src/backend/api/Fusion.Resources.Api/Dockerfile
src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
src/backend/api/Fusion.Resources.Api/Program.cs
src/backend/api/Fusion.Resources.Application/Fusion.Resources.Application.csproj
src/backend/api/Fusion.Resources.Application/ServiceBus/ServiceBusService.cs
src/backend/api/Fusion.Resources.Database/Fusion.Resources.Database.csproj
src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
src/backend/api/Fusion.Resources.Logic/Fusion.Resources.Logic.csproj
src/backend/tests/Fusion.Resources.Api.Tests/Fusion.Resources.Api.Tests.csproj
src/backend/tests/Fusion.Resources.Api.Tests/FusionMocks/EventNotificationClientMock.cs
src/backend/tests/Fusion.Resources.Api.Tests/FusionMocks/TestMessageBus.cs
src/backend/tests/Fusion.Resources.Api.Tests/FusionMocks/TestQueueMessage.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/DirectRequestTests.cs
src/backend/tests/Fusion.Resources.Domain.Tests/Fusion.Resources.Domain.Tests.csproj
src/backend/tests/Fusion.Resources.Functions.Tests/Fusion.Resources.Functions.Tests.csproj
src/backend/tests/Fusion.Resources.Logic.Tests/Fusion.Resources.Logic.Tests.csproj
src/backend/tests/Fusion.Resources.Test.Core/Fusion.Resources.Test.Core.csproj
src/backend/tests/Fusion.Testing.Authentication/Fusion.Testing.Authentication.csproj
src/backend/tests/Fusion.Testing.Core/Fusion.Testing.Core.csproj
src/backend/tests/Fusion.Testing.Mocks.ContextService/Fusion.Testing.Mocks.ContextService.csproj
src/backend/tests/Fusion.Testing.Mocks.LineOrgService/Fusion.Testing.Mocks.LineOrgService.csproj
src/backend/tests/Fusion.Testing.Mocks.OrgService/Fusion.Testing.Mocks.OrgService.csproj
src/backend/tests/Fusion.Testing.Mocks.ProfileService/Fusion.Testing.Mocks.ProfileService.csproj

Update to net7.0
**Testing:**
**Checklist:**

chore: Update to net7.0

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/ProvisionAllocationRequest.cs
src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Provision.cs

Provisioning request endpoint returning 500 due to unhandled exceptions, this is now corrected.
**Testing:**
**Checklist:**

(fix)Api: Added exception handling for provisioning requests 

---

pipelines/pr-cleanup-pipeline.yml

The pr-cleanup function was deleting pr databases from other app-teams. This PRs adds a filter to ensure that only resources  pr-databases are deleted.
**Testing:**
**Checklist:**

fix(pr-cleanup): Only delete resources databases

---

src/backend/function/Fusion.Resources.Functions/ApiClients/ApiModels/LineOrg.cs
src/backend/function/Fusion.Resources.Functions/ApiClients/ILineOrgApiClient.cs
src/backend/function/Fusion.Resources.Functions/ApiClients/LineOrgApiClient.cs
src/backend/function/Fusion.Resources.Functions/Functions/InternalRequestsFunctions.cs
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/Models/DTOs/ScheduledNotificationQueueDto.cs
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ScheduledReportTimerTriggerFunction.cs

All resourceowners under PRD will now receive a weekly report.
The report goes out 8AM every monday.
**Testing:**
**Checklist:**

feat(functions): App departments within PRD is now eligible for weekly report

---

src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ScheduledReportContentBuilderFunction.cs
src/backend/function/Fusion.Resources.Functions/Fusion.Resources.Functions.csproj
src/backend/function/Fusion.Resources.Functions/Integration/Authentication/FunctionTokenProvider.cs
src/backend/function/Fusion.Resources.Functions/ServiceBus/QueueMessageProcessor.cs

The token-provider prevented the team for updating packages due to breaking changes in the packages used by the token-provider.
**Testing:**
**Checklist:**

chore(functions): Tokenprovider updated

---

src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ScheduledReportContentBuilderFunction.cs
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ScheduledReportTimerTriggerFunction.cs

Because the heavy load the notification builder takes on the different api's we need to try to minimize the simultanious processing of the notifications. For this we try to spread the amount of notifications needed over an hour.
**Testing:**
Can be tested with running the notificationScheduler in CI. Check that each of the messages have different sendout time
**Checklist:**

fix: Adjust notifications sendout

---

src/backend/function/Fusion.Resources.Functions/ApiClients/IResourcesApiClient.cs
src/backend/function/Fusion.Resources.Functions/ApiClients/ResourcesApiClient.cs
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ResourceOwnerReportDataCreator.cs
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ScheduledReportContentBuilderFunction.cs
src/backend/tests/Fusion.Resources.Functions.Tests/Notifications/Mock/NotificationReportApiResponseMock.cs

Have removed external personnel (users with accountType=consultant) from summary notifications so that these are not included in the KPI's.
Did also small adjustments regarding getting leave for calculating capacity. It was not necessarry to get this from an own endpoint so I removed it. The calculation is the same.
[AB#49281](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/49281)
**Testing:**
Can be tested with running summary notification and verifying that all personnel of type "consultant" has been removed from the notification. It should be possible to find which users are external personnel by checking in Personnel Allocation for a specific department. All of the external personnel should have the name of their …

feat: Remove external personnel from summary notification

---

src/backend/api/Fusion.Resources.Api/Controllers/Departments/ApiModels/ApiDepartmentResponsible.cs
src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs

Users of type Consultant and Employee should be able to see delegated resource owners. 
Have updated both GET and OPTIONS endpoint for getting delegated resource owners for specific department:
[HttpGet("/departments/{departmentString}/delegated-resource-owners")]
[HttpOptions("/departments/{departmentString}/delegated-resource-owners")]
Both Consultant and Employee should only get limited DepartmentResponsible which means that they don't get the fields "Reason" and "CreatedBy"
[AB#50694](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/50694)
**Testing:**
To test, use postman and try both these endpoints
Endpoint 1: 
GET - https://resources-api-pr-623.fusion-dev.net/departments/{departmentString}/delegated-resource-owne …

feature: Consultant and Employee should get limited Delegated Resource Owners

---

src/backend/function/Fusion.Resources.Functions/ApiClients/IResourcesApiClient.cs
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ResourceOwnerReportDataCreator.cs
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ScheduledReportContentBuilderFunction.cs

The field "Average time to handle request" on the Summary Notification did not give a correct number. The reason was that we checked for that the requests was in state == completed, meaning that we did not include requests that where finished from all parts (resourceowners and taskowners). We want to include requests that have been handled by ResourceOwner, but also those that are still open. 
We have also adjusted so that we include requests for the last 12 months (instead of 3 months).
If we don't find the date for proposal we will use todays date for when calculating the amount of time used to handle a request 
[AB#52911](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/52911)
**Testing:**
Can be tested with running …

fix (resource): Adjust AverageTimeToHandleRequests field on summary notification 

---

src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ResourceOwnerReportDataCreator.cs

Needed to revert to old way of finding the dates of the different states. We need the Workflow.Steps to find the exact date for when a request moves from "Created" to "Proposed", and not just use the date for when a person is proposed (this can be done by the task owner also)
[AB#52911](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/52911)
**Testing:**
Can be tested with running Summary Notifications and check that the value on "Average time to handle request" is correct. May need to manually calculate this value for verify this. See the work item for description on how to test this.
**Checklist:**

fix: Reverted to old way of finding creation date and approval date

---

src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Identifiers/OrgUnitIdentifier.cs
src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/ConversationsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/DepartmentRequestsController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/api/Fusion.Resources.Api/FusionEvents/LineOrgOrgUnitHandler.cs
src/backend/api/Fusion.Resources.Api/Resolvers/OrgUnitResolver.cs
src/backend/api/Fusion.Resources.Api/Resolvers/ProjectResolver.cs
src/backend/api/Fusion.Resources.Api/Swagger/StartupExtensions.cs
src/backend/api/Fusion.Resources.Domain/Commands/Departments/AddDelegatedResourceOwner.cs
src/backend/api/Fusion.Resources.Domain/Identifiers/LineOrgId.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetDelegatedDepartmentResponsibles.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs

Support full department and sap id interchangable in api endpoint routes.
This will enable a switch to primarily use sap id in the frontend, instead of using full department string which is a less stable identifier.
- Updated applicable controllers, keeping exiting expectation of full department string in internal domain intact
- Added some 404 validations where "safe"
- Verified tests are working as expected 
- Added some tests to verify SAP id works in same way as full department string
**Note: PR is forked from #636, many of changes are originating from there.**
**Testing:**
All existing endpoints which accepts full department should support sap id as well. Function should not be changed.
- Added some new tests to verify SAP id along side existing full …

feat: Support SAP id in api routes

---

src/backend/api/Fusion.Resources.Api/FusionEvents/LineOrgEventBody.cs
src/backend/api/Fusion.Resources.Api/FusionEvents/LineOrgOrgUnitHandler.cs
src/backend/api/Fusion.Resources.Api/FusionEvents/LineOrgSyncronizationHandler.cs
src/backend/api/Fusion.Resources.Api/Startup.cs
src/backend/api/Fusion.Resources.Domain/Notifications/System/OrgUnitPathUpdated.cs

When org units are renamed or moved we still persist the old full department string. This can leave requests connected to org units that no longer exists -> orphan requests.
We can subscribe for events comming from line org to act when these changes are done. This should be done as a persistant event handler so we are guaranteed delivery in case of downtime etc.
- Added persistant event handler to perform sync on assigned department for requests
The transient handler are used to invalidate cache, as this is executed on all instances of the api.
**Testing:**
Can be verified by assigning a ticket to some department (use one not commonly used, so we dont cause much problems).
PATCH the org unit in lineorg, chaning the full department (add a character etc).
Verify …

feat: Update assigned department on request when org unit is renamed

---

src/backend/api/Fusion.Resources.Api/FusionEvents/LineOrgSyncronizationHandler.cs
src/backend/api/Fusion.Resources.Domain/Behaviours/AuditableCommandBehaviour.cs
src/backend/api/Fusion.Resources.Domain/Behaviours/MediatorExtension.cs
src/backend/api/Fusion.Resources.Domain/Behaviours/SystemEditorScope.cs
src/backend/api/Fusion.Resources.Domain/Commands/Requests/InternalRequests/UpdateInternalRequest.cs
src/backend/api/Fusion.Resources.Domain/Notifications/System/OrgUnitDeleted.CleanupResponsebilityMatrixHandler.cs
src/backend/api/Fusion.Resources.Domain/Notifications/System/OrgUnitDeleted.DeleteDraftChangeRequestsHandler.cs
src/backend/api/Fusion.Resources.Domain/Notifications/System/OrgUnitDeleted.UnassignAllocationRequestsHandler.cs
src/backend/api/Fusion.Resources.Domain/Notifications/System/OrgUnitDeleted.cs
src/backend/api/Fusion.Resources.Domain/Notifications/System/OrgUnitPathUpdated.cs
src/backend/api/Fusion.Resources.Domain/Services/IProfileServices.cs
src/backend/api/Fusion.Resources.Domain/Services/ProfileServices.cs

As we get more requests and the organisation is re-organising we gather more and more data which is connected to deleted references, e.g deleted org units.
We should try and delete data that will never be relevant (draft requests) and "release" requests that are connected to non-existing units. That way they are at least known to be unassigned.
Updated persistant event handler to publish an `OrgUnitDeleted` notification and two handlers which do solve seperate functionality. Wanted to divide this into smaller functions to increase readability.
Updated "editor" concept to support SystemAccount, when HttpContext is not present. Using Guid.Empty here so we can easily catch it and process it seperately as it will not resolve to an active profile.
**Testing:**
To …

feat: Clean up requests when org unit is deleted

---

src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ScheduledReportContentBuilderFunction.cs
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ScheduledReportTimerTriggerFunction.cs

Configured the worker to start 02:10 instead of 05:00 and also gave the batching job a space of 4.5h to do the job so it does not put a strain on the other APIs. 
**Expected result**: A longer running job with fewer integration errors
**Checklist**:

Feat: Change running config for summary function

---

pipelines/secret-rotation-pipeline.yml

Cron job not triggering because of wrong branch name.

fix: branch name in cronjob

---

pipelines/templates/install-fusion-ps.yml

The pr task to install fusion ps failed due to azure powershell task not updated to support federated credentials.
Changed task to a default powershell task as no azure credentials is needed here.
**Testing:**
Verified in pr
**Checklist:**

chore(pipelines): Fix resource api pr pipeline

---

pipelines/templates/deploy-function-pr-template.yml
pipelines/templates/deploy-function-template.yml
pipelines/templates/deploy-summary-function-pr-template.yml
src/Fusion.Summary.Functions/Deployment/function.template.json
src/Fusion.Summary.Functions/Functions/DepartmentResourceOwnerSync.cs
src/Fusion.Summary.Functions/Fusion.Summary.Functions.csproj
src/Fusion.Summary.Functions/Fusion.Summary.Functions.generated.sln
src/backend/function/Fusion.Resources.Functions/Deployment/function.template.json
src/backend/function/Fusion.Resources.Functions/Fusion.Resources.Functions.csproj
src/backend/function/Fusion.Resources.Functions/local.settings.template.json

In addition to save department to the database the worker should also send the department (id) to the bus for the weekly worker to pick up. Look at Summary notification architecture (https://miro.com/app/board/uXjVN7jm0Tg=/).
**Expected result**: The servicebus queue is utilized to enable the weekly worker
Link to workitem: [LINK](https://statoil-proview.visualstudio.com/Fusion%20Resource%20Allocation/_workitems/edit/53776)
**Checklist**:

Feat: Summary sync puts department on bus

---

pipelines/secret-rotation-pipeline.yml
pipelines/templates/secret-rotation/ensure-secret.yml

The template used the wrong variable name. 
**Expected result**: Pipeline runs again
Link to workitem: [AB#55752](https://statoil-proview.visualstudio.com/Fusion%20Resource%20Allocation/_workitems/edit/55752)
CI pipeline runs after update
**Checklist**:

Fix: Changed pipeline variable name

---

src/Fusion.Resources.Functions.Common/ApiClients/ISummaryApiClient.cs
src/Fusion.Summary.Api/BaseController.cs
src/Fusion.Summary.Api/Controllers/ApiModels/ApiDepartment.cs
src/Fusion.Summary.Api/Controllers/DepartmentsController.cs
src/Fusion.Summary.Api/Controllers/Requests/PutDepartmentRequest.cs
src/Fusion.Summary.Api/Database/Migrations/20240821133720_Initial.Designer.cs
src/Fusion.Summary.Api/Database/Migrations/20240821133720_Initial.cs
src/Fusion.Summary.Api/Database/Migrations/SummaryDbContextModelSnapshot.cs
src/Fusion.Summary.Api/Database/Models/DbDepartment.cs
src/Fusion.Summary.Api/Domain/Commands/CreateDepartment.cs
src/Fusion.Summary.Api/Domain/Commands/UpdateDepartment.cs
src/Fusion.Summary.Api/Domain/Models/QueryDepartment.cs
src/Fusion.Summary.Functions/Deployment/disabled-functions.json
src/Fusion.Summary.Functions/Functions/DepartmentResourceOwnerSync.cs
src/Fusion.Summary.Functions/Functions/WeeklyDepartmentSummarySender.cs
src/Fusion.Summary.Functions/Functions/WeeklyReportSender.cs
src/tests/Fusion.Summary.Api.Tests/HandlerTests/DepartmentTests.cs
src/tests/Fusion.Summary.Api.Tests/Helpers/DepartmentHelpers.cs
src/tests/Fusion.Summary.Api.Tests/IntegrationTests/DepartmentTests.cs

Renamed functions.
Now only takes PRD departmens like the old function did.
The Departments model has been reworked and now has a field for Resource owners and Delegated resource owners. This required refactoring of a lot of code.
For now they're separated into two properties but could be merged into a single recipients list instead,
**Testing:**
**Checklist:**

chore(Summary): Filter departments to PRD and also send report to delegated responsibles

---

infrastructure/arm/environment.template.json

I was a bit quick to merge in the small queue change. I made a typo in defaultMessageTimeToLive timespan format which made it fail.
I should have tested in PR branch before merging in.

fix: Fixed invalid format for defaultMessageTimeToLive value

---

src/Fusion.Resources.Functions.Common/ApiClients/ApiModels/Notifications.cs
src/Fusion.Summary.Functions/CardBuilder/AdaptiveCardBuilder.cs
src/Fusion.Summary.Functions/Functions/WeeklyReportSender.cs
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/AdaptiveCardBuilder.cs
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ScheduledReportContentBuilderFunction.cs
src/backend/function/Fusion.Resources.Functions/Startup.cs

[AB#54653](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/54653)
This PR rewrites the adaptive card code to make it look better. It also adds personnel-allocation app key to the notifcation. This means that if core adds a toggle for personnel allocation, then emails can be turned of for the app. https://github.com/equinor/fusion/issues/390
If we want to perfect the mail design then I believe we'll need to create a separate message and manually send it to the mail service. As I couldn't get the list values to show properly and I couldn't find a way to center the action button. See US https://statoil-proview.visualstudio.com/Fusion%20Resource%20Allocation/_workitems/edit/55681
New design:
Old design:
**Testing:** …

fix: Summary report email layout

---

src/backend/api/Fusion.Resources.Domain/Queries/GetPersonnelAllocation.cs

We don't want product positions (instances) to show up in the list over all allocations in Personnel Allocation, and therefore we need to filter out all these positions.
[AB#55286](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/55286)
[AB#53017](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/53017)
**Testing:**
Can be tested with using endpoint:
https://resources-api-pr-686.fusion-dev.net/departments/{departmentString}/resources/personnel/{personId}?api-version=1.0
Change departmentString with the department you want to check and change personId to a person you want to check. Example "PDP PRD PMC PCA PCA4".
There should be several persons with product positions assigned …

feat: Filter out product positions from GetPersonnelAllocation

---

pipelines/templates/deploy-summary-function-pr-template.yml
src/Fusion.Summary.Functions/Deployment/function.template.json
src/Fusion.Summary.Functions/Functions/DepartmentResourceOwnerSync.cs
src/Fusion.Summary.Functions/local.settings.template.json

[AB#55979](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/55979)
This adds a new setting to the function specifying what departments should be synced and receive reports. The configuration value is a comma separated string. So to only allow departments that contain PRD and TDI => "PRD,TDI".
White space is trimmed and empty values are removed
**Testing:**
**Checklist:**

chore: Department filter configuration for az function

---

src/Fusion.Summary.Api/BaseController.cs
src/Fusion.Summary.Api/Controllers/DepartmentsController.cs
src/Fusion.Summary.Api/Controllers/SummaryReportsController.cs
src/Fusion.Summary.Api/Domain/Commands/PutWeeklySummaryReport.cs
src/Fusion.Summary.Functions/Deployment/disabled-functions.json
src/Fusion.Summary.Functions/Functions/DepartmentResourceOwnerSync.cs
src/Fusion.Summary.Functions/Functions/WeeklyDepartmentSummarySender.cs
src/tests/Fusion.Summary.Api.Tests/IntegrationTests/SummaryReportTests.cs

Transitioned to ProblemDetails, updated status codes for endpoints, removed todos, added some extra tests. Changed time trigger for weekly-department-recipients-sync to only run on monday instead of every day.

chore: Summary cleaup

---

src/Fusion.Resources.Functions.Common/ApiClients/ISummaryApiClient.cs
src/Fusion.Summary.Functions/Functions/DepartmentResourceOwnerSync.cs
src/Fusion.Summary.Functions/Functions/WeeklyDepartmentSummarySender.cs

[AB#55978](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/55978)
- Makes it so that the messages are batched over a time period. This can be configured in az app settings
- Possible to change the amount of concurrency the sync and sender function use in az app settings. Reduced to 2 by defualt
- Refactored some code
- Fixed issue where complex objects weren't logged properly
- Updated timer trigger times
- Added more error handling
**Testing:**
I've tested running the sync function in the PR environment
**Checklist:**

chore(Summary): Spread department messages over batch time

---

src/Fusion.Resources.sln
src/Fusion.Summary.Functions/Functions/DepartmentResourceOwnerSync.cs
src/Fusion.Summary.Functions/Functions/WeeklyDepartmentSummarySender.cs
src/Fusion.Summary.Functions/Functions/WeeklyDepartmentSummaryWorker.cs
src/tests/Fusion.Summary.Functions.Tests/Fusion.Summary.Functions.Tests.csproj
src/tests/Fusion.Summary.Functions.Tests/Notifications/Mock/NotificationReportApiResponseMock.cs
src/tests/Fusion.Summary.Functions.Tests/Notifications/ScheduledReportNotificationBuilderTests.cs
src/tests/Fusion.Summary.Functions.Tests/nuget.config
src/tests/Fusion.Summary.Functions.Tests/xunit.runner.json

Adds more logging and changes log level of some logs.
Added check if the departmentFilter string is emtpy => if empty then do all departments
Added departmentFilter to az sender
Update if any recipients check in the sync az function
**Testing:**
**Checklist:**

chore(summary): Add more logging and other minor fixes

---

src/backend/api/Fusion.Resources.Api/HostedServices/ExpiredDelegatedRolesHostedService.cs
src/backend/api/Fusion.Resources.Database/Entities/DbDelegatedDepartmentResponsibleHistory.cs
src/backend/api/Fusion.Resources.Domain/Commands/Departments/ArchiveDelegatedResourceOwners.cs
src/backend/api/Fusion.Resources.Domain/Notifications/System/OrgUnitDeleted.ArchiveDelegatedResourceOwnersHandler.cs
src/backend/tests/Fusion.Resources.Domain.Tests/DepartmentTests.cs
src/backend/tests/Fusion.Resources.Test.Core/DbTestFixture.cs

[AB#55599](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/55599)
- Adds the command ArchiveDelegatedResourceOwners that archives and removes roles of the specified delegated resource owners
- Adds a new event handler for when an org unit is deleted which calls the new command
**Testing:**
Wrote a unit test for the command. Tested by creating and executing a temporary admin endpoint which calls the archive command.
**Checklist:**

chore(resources): Archive DelegatedResourceOwners when org unit is deleted

---

src/Fusion.Resources.Functions.Common/Integration/Http/Handlers/SummaryHttpHandler.cs
src/Fusion.Summary.Functions/Functions/WeeklyDepartmentSummarySender.cs
src/Fusion.Summary.Functions/host.json

Adds the ability to disable sending of notification within the sender az func. This allows us to dry run the sender for testing.
**Testing:**
**Checklist:**

chore(summary): Add configuration value to disable sending of notification and adjusted logging

---

src/Fusion.Summary.Api/Controllers/ApiModels/ApiPersonnelMoreThan100PercentFTE.cs
src/Fusion.Summary.Api/Database/Migrations/20240916124003_FTE_FromInt_ToDouble.Designer.cs
src/Fusion.Summary.Api/Database/Migrations/20240916124003_FTE_FromInt_ToDouble.cs
src/Fusion.Summary.Api/Database/Models/DbWeeklySummaryReport.cs
src/Fusion.Summary.Api/Domain/Models/QueryWeeklySummaryReport.cs
src/tests/Fusion.Summary.Api.Tests/Helpers/SummaryReportHelpers.cs

Changes the db type of FTE from int to double.

fix(summary): Use double instead of int for FTE

---

src/Fusion.Resources.Functions.Common/Fusion.Resources.Functions.Common.csproj
src/Fusion.Summary.Api/Fusion.Summary.Api.csproj
src/Fusion.Summary.Api/Program.cs
src/backend/Fusion.Resources.Authorization/Fusion.Resources.Authorization.csproj
src/backend/Fusion.Resources.Infrastructure/Fusion.Resources.Infrastructure.csproj
src/backend/api/Fusion.Resources.Api/Controllers/Personnel/InternalPersonnelController.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/AnalyticsController.cs
src/backend/api/Fusion.Resources.Api/Fusion.Resources.Api.csproj
src/backend/api/Fusion.Resources.Api/Startup.cs
src/backend/api/Fusion.Resources.Application/Fusion.Resources.Application.csproj
src/backend/api/Fusion.Resources.Database/Fusion.Resources.Database.csproj
src/backend/api/Fusion.Resources.Domain/Fusion.Resources.Domain.csproj
src/backend/tests/Fusion.Resources.Api.Tests/Fusion.Resources.Api.Tests.csproj
src/backend/tests/Fusion.Resources.Domain.Tests/Fusion.Resources.Domain.Tests.csproj
src/backend/tests/Fusion.Resources.Functions.Tests/Fusion.Resources.Functions.Tests.csproj
src/backend/tests/Fusion.Resources.Logic.Tests/Fusion.Resources.Logic.Tests.csproj
src/backend/tests/Fusion.Resources.Test.Core/Fusion.Resources.Test.Core.csproj
src/backend/tests/Fusion.Testing.Authentication/Fusion.Testing.Authentication.csproj
src/backend/tests/Fusion.Testing.Core/Fusion.Testing.Core.csproj
src/backend/tests/Fusion.Testing.Mocks.ContextService/Fusion.Testing.Mocks.ContextService.csproj
src/backend/tests/Fusion.Testing.Mocks.LineOrgService/Fusion.Testing.Mocks.LineOrgService.csproj
src/backend/tests/Fusion.Testing.Mocks.OrgService/Fusion.Testing.Mocks.OrgService.csproj
src/backend/tests/Fusion.Testing.Mocks.ProfileService/Api/PersonsController.cs
src/backend/tests/Fusion.Testing.Mocks.ProfileService/Fusion.Testing.Mocks.ProfileService.csproj
src/tests/Fusion.Summary.Api.Tests/Fusion.Summary.Api.Tests.csproj

[AB#55718](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/55718)
This updates all packages to the latest version. ~excluding Fusion.AspNetCore. Fusion.AspNetCore version above 7.0.1 causes the PatchModelBinder to fail to parse PatchProperty<ApiPropertiesCollection?> properties in patch requests.~
~Where PatchProperty with ApiPropertiesCollection will always be empty. I have created an issue for this: https://github.com/equinor/fusion/issues/400~
Issue has been closed and I've added the newest Fusion.AspNetCore version to this PR
**Testing:**
**Checklist:**

chore(resources): Packages update

---

src/Fusion.Summary.Api/Program.cs
src/backend/api/Fusion.Resources.Api/Startup.cs

Frontend are showing the x-trace-id available from response headers in a api request, but as the resources and summary services did not expose the x-trace-id it was shown as null. 
[AB#56897](https://statoil-proview.visualstudio.com/Fusion%20Resource%20Allocation/_boards/board/t/Fusion%20Resource%20Allocation%20Team/Stories/?workitem=56897)
**Testing:**
Can be tested manually by looking at the response headers from any requests to the resources or summary api (absence request on landing page) and verifying that x-trace-id is under the access-control-expose-headers like this
access-control-expose-headers: Allow,x-fusion-retriable,x-trace-id
**Checklist:**

chore: expose x-trace-id in response headers

---

pipelines/environment-pipeline.yml

When deploying infra IAC the PR env would fail because it would soft delete the secret but not purge it. With this PR it will instead be disabled.
Example of a pipeline run that fails
https://statoil-proview.visualstudio.com/Fusion%20Resource%20Allocation/_build/results?buildId=131253&view=logs&j=013c5867-0d4e-5d8f-4115-5efe4ac203c0&t=bc5fcbcb-7453-5c1d-5540-a7bbd223bfa7&s=2741fbd7-98d1-5541-d761-9bcc81bce3d2
I've circumvented this earlier by **personally** purging the secret myself 😡
**Testing:**
Ran this pipeline and created a PR that ran resource api. Then tested that it could talk to the DB. TEST PR #720 
**Checklist:**

chore(iac): Disable resources connection string for PR env instead of soft deleting it

---

pipelines/templates/deploy-summary-function-pr-template.yml
pipelines/templates/deploy-summary-function-template.yml
src/Fusion.Resources.Functions.Common/ApiClients/LineOrgApiClient.cs
src/Fusion.Summary.Functions/Functions/DepartmentResourceOwnerSync.cs
src/backend/api/Fusion.Resources.Api/libman.json
src/backend/function/Fusion.Resources.Functions/Functions/Notifications/ResourceOwner/WeeklyReport/ScheduledReportTimerTriggerFunction.cs
src/backend/function/Fusion.Resources.Functions/Fusion.Resources.Functions.csproj

Adjusted the department filter to target department of level 4 and above
**Expected result**: Summary reports only targets level 4 departments and above
Link to workitem: [LINK](https://statoil-proview.visualstudio.com/Fusion%20Resource%20Allocation/_workitems/edit/23812)
**Checklist**:

Feat #23812 - Adjust resource owner recipients

---

src/backend/api/Fusion.Resources.Domain/Models/QueryOrgUnitReason.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetRelevantOrgUnits.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetResourceOwnerProfile.cs

Get person departments was missed when aligning endpoints to use fusion roles for manager responebility instead of isResourceOwner and fullDepartment.
**Testing:**
**Checklist:**

fix: Fixed profile and relevant-department to resolve correctly after workday update

---

src/backend/api/Fusion.Resources.Api/Controllers/Person/ApiModels/ApiPersonAllocationRequestStatus.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/PersonController.cs

After change to the departments for managers all direct requests are now added to incorrect org unit. This means the manager of the inteded manager is now getting notifications about requests.
**Testing:**
TBD
**Checklist:**

fix: Direct requests assigned to incorrect org unit

---

src/Fusion.Summary.Api/Deployment/k8s/deployment-ingress-test.yml
src/Fusion.Summary.Api/Deployment/k8s/pr-deployment-env.yml
src/backend/api/Fusion.Resources.Api/Deployment/k8s/deployment-ingress-test.yml
src/backend/api/Fusion.Resources.Api/Deployment/k8s/pr-deployment-env.yml

The ingress class name in pre-prod cluster is now ingress-nginx-fusiondev
**Testing:**
**Checklist:**

feat(k8s): Update ingress class name for pre-prod-cluster

---

src/Fusion.Summary.Functions/Functions/DepartmentResourceOwnerSync.cs

The sync took too long, I've added parallelism to the two main loops fetching and building data. Set the number of threads to 2 which should double the amount of work being done, ish...
**Testing:**
**Checklist:**

Added parallelism to sync

---

src/Fusion.Summary.Functions/Functions/TaskOwnerReports/WeeklyTaskOwnerReportSender.cs

Allow for disabling sending of notification for **only** weekly task owner sender. This will allow us to test it without sending the report
**Testing:**
Ran pipeline with this PR. Did a dry run in prod
**Checklist:**

feat: Allow disabling of only WeeklyTaskOwnerReportSender

---

src/backend/Fusion.Resources.Infrastructure/Swagger/SwaggerSetup.cs

To fix this swagger gen error
System.InvalidOperationException: Can't use schemaId "$ApiPerson" for type "$Fusion.Services.LineOrg.ApiModels.ApiPerson". The same schemaId is already used for type "$Fusion.Resources.Api.Controllers.ApiPerson"
**Testing:**
**Checklist:**

fix(common): Duplicate schemaId error during swagger gen

---

src/backend/api/Fusion.Resources.Domain/Queries/GetResourceOwnerProfile.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonControllerTests.cs

Work Item: [AB#60494](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/60494)
Added a check to ensure departments exist before adding to list of delegated responsibilities. This issue occurred because a department was removed with active delegated responsibles without removing them as well. This will ensure the api returns valid data, but the PIMS sync should remove the delegated responsibles.
**Testing:**
Unable to test with the current mock of the LineOrgService. There is no ability to remove departments. The existing tests do confirm that it is working correctly under normal circumstances. It has been/can be tested in swagger with the user that reported the bug.
**Checklist:**

fix: only return existing departments when fetching responsibilities. 

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs

[AB#60124](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/60124)
Resource owners and users with scoped resource owner role (DelegatedResourceOwner), can now delete requests that are invalid. Invalid in that the position or position instance that the request is targeting, has has been deleted.
See WorkItem comments for more details
**Testing:**
**Checklist:**

feat(resources): Allow resource owners to delete invalid requests in assgined and child departments

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/PatchInternalRequestRequest.cs
src/backend/api/Fusion.Resources.Domain/Commands/Requests/InternalRequests/UpdateInternalRequest.cs
src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Allocation/ProvisionAllocationRequest.cs
src/backend/tests/Fusion.Resources.Logic.Tests/Provisioning/AllocationTests.cs

[AB#54170](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/54170)
Connected frontend PR: https://github.com/equinor/fusion-resource-allocation-apps/pull/862
- Now possible for a resource owner to propose a different base position for the allocation request
**Testing:**
Added a test cases for proposed changes. Also did testing through PR frontend connected to this PR
**Checklist:**

feat(resources): Added option to propose another basePosition for an allocation request

---

src/backend/api/Fusion.Resources.Api/Controllers/Person/Requests/CreatePersonAbsenceRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Person/Requests/UpdatePersonAbsenceRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs
src/backend/tests/Fusion.Resources.Api.Tests/AuthorizationTests/SecurityMatrixTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/ApiHelpers.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationNotificationTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/PersonAbsenceTests.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Helpers/ApiPositionV2Extensions.cs
src/backend/tests/Fusion.Testing.Mocks.OrgService/Helpers/PositionInstanceBuilder.cs

Added location requirement to validation of CreatePersonAbsenceRequest and UpdatePersonAbsenceRequest for absences of type `OtherTasks`.
Added the method `LocationWillBeNull` to the `InternalRequestsController` class to check that a location will be set for the following endpoints:
- [HttpPost("/departments/{departmentString}/resources/requests")]
- [HttpPatch("/resources/requests/internal/{requestId}")]
- [HttpPatch("/departments/{departmentString}/resources/requests/{requestId}")]
The logic is a little complicated, it needs to ensure that after changes will have been applied the request will have a valid location. It needs to take into account whether the request already has a position, if a location is being proposed, and that the proposed location isn't null, …

feat: require location in validation for other tasks

---

src/backend/api/Fusion.Resources.Api/FusionEvents/OrgProjectHandler.cs
src/backend/api/Fusion.Resources.Domain/Commands/BaseHandlers/ResponsibilityMatrixBaseHandler.cs
src/backend/api/Fusion.Resources.Domain/Commands/Projects/SyncProjectStates.cs
src/backend/api/Fusion.Resources.Domain/Commands/Requests/InternalRequests/CreateInternalRequest.cs
src/backend/api/Fusion.Resources.Domain/Extensions/StringExtensions.cs
src/backend/api/Fusion.Resources.Domain/Models/QueryProject.cs
src/backend/api/Fusion.Resources.Domain/Queries/GetTBNPositions.cs
src/backend/tests/Fusion.Resources.Api.Tests/FusionEventHandlerTests/ProjectSync.cs
src/backend/tests/Fusion.Resources.Api.Tests/Helpers/Models/Responses/TestApiProjectReference.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentRequestsTests.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalResourceAllocationRequestTests.cs

Link to work item: [AB#60951](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/60951)
Multi-pronged approach setting the project state to `"ACTIVE"` if it is null. This is done in the `QueryProject` and `QueryProjectRef` constructors when querying projects, when projects are added to the database, and when projects are synced with org. Over time all null values should be replaced in the database, and the check in the query layer will act as a failsafe.
Created a string extension to set the state correctly, this will also allow for adding checks in the future.
**Testing:**
**Checklist:**

fix: api should not return null for project state

---

src/Fusion.Summary.Functions/Functions/DepartmentResourceOwnerSync.cs
src/Fusion.Summary.Functions/Functions/WeeklyDepartmentSummarySender.cs

[AB#61612](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/61612)
Bandaid fix for az func timing out. A resource owner is not getting the report because the azure func times out before being able to send the report...
Should consider reworking or optimizing the architecture surrounding summary reports
**Testing:**
**Checklist:**

fix: Add logging and increased default parallelism for weekly department sender

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs

[AB#61687](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/61687)
Seems it was a bit too strict to check for location when patching a request. Now instead of ensuring a location is set when patching a request, it is instead ensured when the request is proposed from the resource owner side.
As with many of these endpoints, there is some business logic placed in the frontend and backend...
**Testing:**
**Checklist:**

fix(resources): Allow location to be null when patching a request

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/InternalRequestsController.cs

[AB#62391](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/62391)
Ensure that location is not null only for adjustment resource owner requests.
**Testing:**
**Checklist:**

fix(resources): Require location only for adjusment resource owner requests

---

src/Fusion.Summary.Api/Controllers/ApiModels/ApiReportMetaData.cs
src/Fusion.Summary.Api/Controllers/ApiModels/ApiWeeklySummaryReport.cs
src/Fusion.Summary.Api/Domain/Models/QueryReportMetaData.cs
src/Fusion.Summary.Api/Domain/Models/QueryWeeklySummaryReport.cs

To make it less confusing what period means on the resource owner report, a new propery PeriodEnd has been added. This is calculated during query instead of being stored in db,
**Testing:**
**Checklist:**

feat(summary): Add synthetic periodEnd property

---

src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/PatchInternalRequestRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Requests/Requests/ProposalParametersRequest.cs
src/backend/api/Fusion.Resources.Api/Controllers/Validation/CustomValidatorExtensions.cs

[AB#62551](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/62551)
OrgService works with dates and the time component is uneeded. Avoid potential issues with timezones give the FE feedback immediately instead of later in the proviosning process
Frontend currently sends inccorect date time so https://github.com/equinor/fusion-resource-allocation-apps/pull/1079 needs to go out first
**Testing:**
**Checklist:**

fix(resources): Ensure date's time component is set to 00:00:00 for proposed changes

---

src/backend/api/Fusion.Resources.Logic/Requests/Commands/ResourceAllocationRequest/Approve.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/InternalRequests/DirectRequestTests.cs

If a resource owner sets the location for a direct request, and the project had left it empty, the project should not have to
approve the location change. 
Updated the logic in `AnyProposedChanges` in Approve.cs to reflect this.
[AB#62464](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/62464)
**Testing:**
**Checklist:**

feat: auto approve direct requests where resource owner sets location

---

src/backend/api/Fusion.Resources.Api/Authorization/Extensions/RequirementsBuilderExtensions.cs
src/backend/tests/Fusion.Resources.Api.Tests/IntegrationTests/DepartmentsControllerTests.cs

[AB#62509](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/62509)
Allow resource owners to only assign delegated resource owners in current, sibling and direct child departments. 
**Testing:**
**Checklist:**

feat(resources): Allow resource owners to assign delegated resource owners in sibling departments

---

src/Fusion.Resources.Functions.Common/ApiClients/ISummaryApiClient.cs
src/Fusion.Summary.Api/Controllers/ApiModels/ApiWeeklySummaryReport.cs
src/Fusion.Summary.Api/Controllers/Requests/PutWeeklySummaryReportRequest.cs
src/Fusion.Summary.Api/Database/Migrations/20250730120409_OpenRequestsWorkload_to_db_column.Designer.cs
src/Fusion.Summary.Api/Database/Migrations/20250730120409_OpenRequestsWorkload_to_db_column.cs
src/Fusion.Summary.Api/Database/Models/DbWeeklySummaryReport.cs
src/Fusion.Summary.Api/Domain/Commands/PutWeeklySummaryReport.cs
src/Fusion.Summary.Api/Domain/Models/QueryWeeklySummaryReport.cs
src/Fusion.Summary.Api/appsettings.json
src/Fusion.Summary.Functions/Functions/WeeklyDepartmentSummarySender.cs
src/Fusion.Summary.Functions/Functions/WeeklyDepartmentSummaryWorker.cs
src/Fusion.Summary.Functions/ReportCreator/ResourceOwnerReportDataCreator.cs
src/tests/Fusion.Summary.Api.Tests/Helpers/SummaryReportHelpers.cs
src/tests/Fusion.Summary.Functions.Tests/Notifications/ScheduledReportNotificationBuilderTests.cs

- [ x] New feature
Added a propery to summary report db -> OpenRequestsWorkload
Calculate the combined workload of all open requests and returns the percentage based on available capacity
[AB#64175](https://statoil-proview.visualstudio.com/787035c2-8cf2-4d73-a83e-bb0e6d937eec/_workitems/edit/64175)
**Testing:**
- [x ] Can be tested
**Checklist:**

feat: add open requests workload
